# -*- coding: utf-8 -*-
"""Неделя 2: 12–16 октября."""
from h import w, C, L, G, J, M, O, D, T, ex, th, topic, hw

CONTENT = {}

# ---------------------------------------------------------------- 12 октября
CONTENT["2026-10-12"] = {
    "topic": "Возвратные глаголы · распорядок дня",
    "theory": [
        th("Глагол + себя",
           "Возвратные глаголы (verbes pronominaux) — это глаголы с частицей se: se lever — вставать, se laver — мыться. Частица меняется вместе с лицом: me, te, se, nous, vous, se.",
           table=[["je me lave", "я моюсь"], ["tu te laves", "ты моешься"], ["il / elle se lave", "он / она моется"], ["nous nous lavons", "мы моемся"], ["vous vous lavez", "вы моетесь"], ["ils / elles se lavent", "они моются"]]),
        th("Перед гласной — m’, t’, s’",
           "s’habiller — одеваться: je m’habille, tu t’habilles, il s’habille.",
           exs=[["Je m’habille vite.", "Я быстро одеваюсь."], ["Elle s’appelle Léa.", "Её зовут Леа."]]),
        th("se lever — с ударением",
           "В формах, где окончание не слышно, e превращается в è: je me lève, tu te lèves, ils se lèvent, но nous nous levons, vous vous levez.",
           exs=[["Je me lève à sept heures.", "Я встаю в семь."], ["Nous nous levons tôt.", "Мы встаём рано."]]),
        th("Отрицание",
           "ne ставится перед частицей, pas — после глагола: je ne me lève pas.",
           exs=[["Je ne me couche pas tard.", "Я не ложусь поздно."], ["Il ne se rase pas.", "Он не бреется."]]),
    ],
    "vocab": [
        w("se-reveiller", "se réveiller", "просыпаться", "Je me réveille à six heures.", "Я просыпаюсь в шесть.", forms=["réveille", "réveilles", "réveillons", "réveillez", "réveillent"]),
        w("se-lever", "se lever", "вставать", "Tu te lèves tôt ?", "Ты рано встаёшь?", forms=["lève", "lèves", "levons", "levez", "lèvent"]),
        w("se-laver", "se laver", "мыться", "Il se lave.", "Он моется.", forms=["lave", "laves", "lavons", "lavez", "lavent"]),
        w("se-doucher", "se doucher", "принимать душ", "Je me douche le matin.", "Я принимаю душ утром.", forms=["douche", "douches", "douchons", "douchez", "douchent"]),
        w("se-brosser", "se brosser les dents", "чистить зубы", "Je me brosse les dents.", "Я чищу зубы.", forms=["brosse", "brosses"]),
        w("s-habiller", "s’habiller", "одеваться", "Elle s’habille.", "Она одевается.", forms=["habille", "habilles", "habillons", "habillez", "habillent"]),
        w("se-maquiller", "se maquiller", "краситься", "Je me maquille vite.", "Я быстро крашусь.", forms=["maquille", "maquilles"]),
        w("se-preparer", "se préparer", "собираться", "Je me prépare pour le travail.", "Я собираюсь на работу.", forms=["prépare", "prépares"]),
        w("se-depecher", "se dépêcher", "торопиться", "Dépêche-toi !", "Поторопись!", forms=["dépêche", "dépêches", "dépêchons"]),
        w("s-appeler", "s’appeler", "называться, зваться", "Comment tu t’appelles ?", "Как тебя зовут?", forms=["appelles", "appelle"]),
        w("se-reposer", "se reposer", "отдыхать", "Le dimanche, je me repose.", "В воскресенье я отдыхаю.", forms=["repose", "reposes", "reposons"]),
        w("se-promener", "se promener", "гулять", "On se promène au parc.", "Мы гуляем в парке.", forms=["promène", "promènes", "promenons"]),
        w("s-amuser", "s’amuser", "развлекаться", "Les enfants s’amusent.", "Дети веселятся.", forms=["amuse", "amusent"]),
        w("se-coucher", "se coucher", "ложиться спать", "Je me couche à minuit.", "Я ложусь в полночь.", forms=["couche", "couches", "couchons", "couchez", "couchent"]),
        w("tot", "tôt", "рано", "Je me lève tôt.", "Я встаю рано."),
        w("tard", "tard", "поздно", "Il se couche tard.", "Он ложится поздно."),
    ],
    "topics": [
        topic("t-pronominaux", "Возвратные глаголы",
              ("je ___ lève", ["me", "se", "te"]),
              ("nous ___ promenons", ["nous", "se", "vous"]),
              ("«Я не встаю рано»", ["Je ne me lève pas tôt.", "Je me ne lève pas tôt.", "Je ne lève me pas tôt."])),
    ],
    "exercises": ex(
        J("se laver", [["je", "me lave"], ["tu", "te laves"], ["il", "se lave"], ["nous", "nous lavons"], ["vous", "vous lavez"], ["ils", "se lavent"]]),
        J("se lever", [["je", "me lève"], ["tu", "te lèves"], ["elle", "se lève"], ["nous", "nous levons"], ["vous", "vous levez"], ["elles", "se lèvent"]]),
        G("Je ___ réveille à sept heures.", "Я просыпаюсь в семь.", "me"),
        G("Tu ___ couches tard ?", "Ты поздно ложишься?", "te"),
        G("Nous ___ promenons le dimanche.", "Мы гуляем по воскресеньям.", "nous"),
        G("Elle s’___ très vite.", "Она очень быстро одевается. (s’habiller)", "habille"),
        G("Ils se ___ les dents.", "Они чистят зубы. (se brosser)", "brossent"),
        C("Как правильно?", ["Je m’habille.", "Je me habille.", "Je s’habille."]),
        C("Как правильно?", ["Je ne me lève pas tôt.", "Je me ne lève pas tôt.", "Je ne lève pas me tôt."]),
        L("Vous vous levez tôt ?", ["Vous vous levez tôt ?", "Vous levez tôt ?", "Nous nous levons tôt ?"]),
        M("Утро и вечер", [["se réveiller", "просыпаться"], ["se doucher", "принимать душ"], ["s’habiller", "одеваться"], ["se coucher", "ложиться спать"], ["se dépêcher", "торопиться"]]),
        O("Собери фразу «Я ложусь в одиннадцать»", ["me", "Je", "à", "couche", "onze", "heures"], "je me couche à onze heures"),
        O("Собери фразу «Он не бреется»", ["ne", "Il", "rase", "se", "pas"], "il ne se rase pas"),
        D("Il se brosse les dents.", "il se brosse les dents"),
        D("Nous nous dépêchons.", "nous nous dépêchons"),
        T("Я просыпаюсь в семь.", "je me réveille à sept heures", "je me réveille à 7 heures", "je me réveille à 7h"),
        T("Она одевается.", "elle s'habille"),
        T("Мы отдыхаем.", "nous nous reposons", "on se repose"),
    ),
    "homework": hw("Опиши своё обычное утро и вечер, используя 6–8 возвратных глаголов: во сколько просыпаешься, встаёшь, что делаешь потом, когда ложишься спать.",
                   "Je me réveille à sept heures. Je me lève tout de suite. Je me douche et je m’habille. Le soir, je me repose. Je me couche à minuit.", 25),
}

# ---------------------------------------------------------------- 13 октября
CONTENT["2026-10-13"] = {
    "topic": "Притяжательные · спорт и музыка",
    "theory": [
        th("Мой, твой, его…",
           "Притяжательное слово согласуется с тем, что принадлежит, а не с владельцем: sa maison — «его дом» и «её дом». Перед гласной в женском роде — mon, ton, son: mon amie.",
           table=[["mon / ma / mes", "мой / моя / мои"], ["ton / ta / tes", "твой"], ["son / sa / ses", "его, её"], ["notre / nos", "наш"], ["votre / vos", "ваш"], ["leur / leurs", "их"]]),
        th("Спорт: jouer à и faire de",
           "Игры с мячом и правилами — jouer à: jouer au football, au tennis. Остальное — faire de: faire du vélo, de la natation, du yoga.",
           exs=[["Je joue au tennis.", "Я играю в теннис."], ["Elle fait de la natation.", "Она занимается плаванием."], ["On fait du vélo.", "Мы катаемся на велосипеде."]]),
        th("Музыка: jouer de",
           "На инструментах «играют из»: jouer du piano, de la guitare, du violon.",
           exs=[["Mon frère joue de la guitare.", "Мой брат играет на гитаре."], ["Tu joues du piano ?", "Ты играешь на пианино?"]]),
    ],
    "vocab": [
        w("football", "le football / le foot", "футбол", "Il joue au foot.", "Он играет в футбол.", "m", ["football", "foot"]),
        w("tennis", "le tennis", "теннис", "Je joue au tennis.", "Я играю в теннис.", "m"),
        w("basket", "le basket", "баскетбол", "On joue au basket ?", "Поиграем в баскетбол?", "m"),
        w("natation", "la natation", "плавание", "Je fais de la natation.", "Я занимаюсь плаванием.", "f"),
        w("velo", "le vélo", "велосипед", "Je fais du vélo.", "Я катаюсь на велосипеде.", "m", ["vélo"]),
        w("course", "la course à pied", "бег", "La course à pied, c’est bon pour la santé.", "Бег полезен для здоровья.", "f", ["course"]),
        w("ski", "le ski", "лыжи", "On fait du ski en hiver.", "Зимой катаемся на лыжах.", "m"),
        w("danse", "la danse", "танцы", "Elle fait de la danse.", "Она занимается танцами.", "f"),
        w("yoga", "le yoga", "йога", "Je fais du yoga le soir.", "Я занимаюсь йогой вечером.", "m"),
        w("randonnee", "la randonnée", "поход", "J’aime faire de la randonnée.", "Люблю ходить в походы.", "f"),
        w("piano", "le piano", "пианино", "Tu joues du piano ?", "Ты играешь на пианино?", "m"),
        w("guitare", "la guitare", "гитара", "Il joue de la guitare.", "Он играет на гитаре.", "f"),
        w("violon", "le violon", "скрипка", "Elle joue du violon.", "Она играет на скрипке.", "m"),
        w("batterie", "la batterie", "барабаны (ударная установка)", "Je joue de la batterie.", "Я играю на барабанах.", "f"),
        w("flute", "la flûte", "флейта", "La flûte est jolie.", "Флейта красивая.", "f"),
        w("sport", "le sport", "спорт", "Tu fais du sport ?", "Ты занимаешься спортом?", "m"),
        w("passe-temps", "un passe-temps", "хобби, увлечение", "Mon passe-temps, c’est la danse.", "Моё хобби — танцы.", "m"),
    ],
    "topics": [
        topic("t-possessifs", "Притяжательные",
              ("___ sœur (моя)", ["ma", "mon", "mes"]),
              ("___ amie (моя)", ["mon", "ma", "mes"]),
              ("___ enfants (их)", ["leurs", "leur", "ses"])),
        topic("t-jouer", "jouer à / jouer de / faire de",
              ("Я играю в теннис", ["Je joue au tennis.", "Je joue du tennis.", "Je fais au tennis."]),
              ("Он играет на гитаре", ["Il joue de la guitare.", "Il joue à la guitare.", "Il fait la guitare."]),
              ("Она занимается плаванием", ["Elle fait de la natation.", "Elle joue à la natation.", "Elle fait la natation."])),
    ],
    "exercises": ex(
        C("___ sœur (моя)", ["ma", "mon", "mes"]),
        C("___ amie (моя)", ["mon", "ma"]),
        C("___ parents (наши)", ["nos", "notre"]),
        C("___ enfants (их)", ["leurs", "leur"]),
        G("Paul aime ___ vélo.", "Поль любит свой велосипед.", "son"),
        G("Marie cherche ___ guitare.", "Мари ищет свою гитару.", "sa"),
        G("Je joue ___ tennis.", "Я играю в теннис.", "au"),
        G("Elle joue ___ piano.", "Она играет на пианино.", "du"),
        G("Nous faisons ___ natation.", "Мы занимаемся плаванием.", "de la"),
        G("Il fait ___ vélo le dimanche.", "Он катается на велосипеде по воскресеньям.", "du"),
        L("mon amie", ["mon amie", "ma amie", "mes amies"]),
        M("Спорт и музыка", [["la natation", "плавание"], ["la course à pied", "бег"], ["le violon", "скрипка"], ["la batterie", "барабаны"], ["la randonnée", "поход"]]),
        O("Собери фразу «Мой брат играет на гитаре»", ["joue", "Mon", "frère", "guitare", "la", "de"], "mon frère joue de la guitare"),
        D("Tu fais du sport ?", "tu fais du sport"),
        D("Ses amis jouent au basket.", "ses amis jouent au basket"),
        T("Я играю в футбол.", "je joue au football", "je joue au foot"),
        T("Её брат играет на скрипке.", "son frère joue du violon"),
        T("Наша дочь занимается танцами.", "notre fille fait de la danse"),
    ),
    "homework": hw("Расскажи о хобби: чем занимаешься ты, твои друзья или родные. Используй mon/ma/mes, son/sa/ses и конструкции jouer à, jouer de, faire de. 5–6 предложений.",
                   "Je fais du yoga. Mon frère joue au foot. Ma sœur joue du piano. Son mari fait du vélo. Nos amis font de la randonnée.", 20),
}

# ---------------------------------------------------------------- 14 октября
CONTENT["2026-10-14"] = {
    "topic": "Прилагательные: мужской и женский род",
    "theory": [
        th("Основное правило: + e",
           "Женский род обычно образуется добавлением -e: grand → grande, blond → blonde. Немая согласная при этом начинает звучать: petit [пти] → petite [птит]. Если слово уже кончается на -e, ничего не меняется: jeune, calme, timide.",
           exs=[["Il est grand, elle est grande.", "Он высокий, она высокая."], ["Il est jeune, elle est jeune.", "Он молодой, она молодая."]]),
        th("Типичные окончания",
           "Некоторые окончания меняются по-своему.",
           table=[["-eux → -euse", "heureux → heureuse"], ["-if → -ive", "sportif → sportive"], ["-ien → -ienne", "italien → italienne"], ["-er → -ère", "cher → chère"], ["-eur → -euse", "travailleur → travailleuse"], ["-il → -ille", "gentil → gentille"]]),
        th("Неправильные",
           "beau → belle, nouveau → nouvelle, vieux → vieille, blanc → blanche, long → longue, roux → rousse.",
           exs=[["un beau garçon, une belle fille", "красивый мальчик, красивая девочка"], ["un vieux livre, une vieille maison", "старая книга, старый дом"]]),
        th("Где стоит прилагательное",
           "Обычно после существительного: une femme intelligente. Но короткие частые — красота, возраст, «хороший/плохой», размер — стоят перед ним: un petit chat, une belle maison, un bon ami.",
           exs=[["une femme intelligente", "умная женщина"], ["un petit chat", "маленький кот"]]),
    ],
    "vocab": [
        w("jeune", "jeune", "молодой", "Elle est jeune.", "Она молодая.", forms=["jeunes"]),
        w("vieux", "vieux / vieille", "старый / старая", "Un vieux monsieur.", "Пожилой господин.", forms=["vieux", "vieille", "vieil"]),
        w("beau", "beau / belle", "красивый / красивая", "Quelle belle journée !", "Какой прекрасный день!", forms=["beau", "belle", "beaux", "belles", "bel"]),
        w("joli", "joli / jolie", "симпатичный, милый", "Une jolie robe.", "Красивое платье.", forms=["joli", "jolie"]),
        w("gentil", "gentil / gentille", "добрый, милый", "Il est très gentil.", "Он очень добрый.", forms=["gentil", "gentille"]),
        w("sympa", "sympa", "приятный, классный (разг.)", "Ton ami est sympa.", "Твой друг классный."),
        w("intelligent", "intelligent / intelligente", "умный", "Une fille intelligente.", "Умная девушка.", forms=["intelligent", "intelligente"]),
        w("drole", "drôle", "смешной, весёлый", "Il est drôle.", "Он смешной."),
        w("serieux", "sérieux / sérieuse", "серьёзный", "Elle est sérieuse.", "Она серьёзная.", forms=["sérieux", "sérieuse"]),
        w("timide", "timide", "застенчивый", "Je suis un peu timide.", "Я немного застенчивая."),
        w("heureux", "heureux / heureuse", "счастливый", "Je suis heureuse.", "Я счастлива.", forms=["heureux", "heureuse"]),
        w("triste", "triste", "грустный", "Pourquoi tu es triste ?", "Почему ты грустишь?"),
        w("mince", "mince", "стройный, худой", "Elle est mince.", "Она стройная."),
        w("fort", "fort / forte", "сильный", "Il est fort.", "Он сильный.", forms=["fort", "forte"]),
        w("blond", "blond / blonde", "светловолосый", "Une femme blonde.", "Блондинка.", forms=["blond", "blonde"]),
        w("brun", "brun / brune", "темноволосый", "Il est brun.", "Он брюнет.", forms=["brun", "brune"]),
        w("roux", "roux / rousse", "рыжий", "Elle est rousse.", "Она рыжая.", forms=["roux", "rousse"]),
        w("sportif", "sportif / sportive", "спортивный", "Ma mère est sportive.", "Моя мама спортивная.", forms=["sportif", "sportive"]),
        w("calme", "calme", "спокойный", "C’est un enfant calme.", "Это спокойный ребёнок."),
        w("curieux", "curieux / curieuse", "любопытный", "Je suis curieuse.", "Мне любопытно.", forms=["curieux", "curieuse"]),
        w("genereux", "généreux / généreuse", "щедрый", "Il est généreux.", "Он щедрый.", forms=["généreux", "généreuse"]),
        w("paresseux", "paresseux / paresseuse", "ленивый", "Le chat est paresseux.", "Кот ленивый.", forms=["paresseux", "paresseuse"]),
        w("travailleur", "travailleur / travailleuse", "трудолюбивый", "Elle est très travailleuse.", "Она очень трудолюбивая.", forms=["travailleur", "travailleuse"]),
        w("cher", "cher / chère", "дорогой", "C’est trop cher.", "Это слишком дорого.", forms=["cher", "chère"]),
    ],
    "topics": [
        topic("t-adj", "Женский род прилагательных",
              ("heureux →", ["heureuse", "heureuxe", "heureusse"]),
              ("sportif →", ["sportive", "sportife", "sportiffe"]),
              ("beau →", ["belle", "beaue", "bele"]),
              ("gentil →", ["gentille", "gentile", "gentil"])),
    ],
    "exercises": ex(
        C("heureux → женский род", ["heureuse", "heureuxe"]),
        C("sportif → женский род", ["sportive", "sportife"]),
        C("beau → женский род", ["belle", "beaue"]),
        C("gentil → женский род", ["gentille", "gentile"]),
        G("Ma sœur est ___.", "Моя сестра высокая. (grand)", "grande"),
        G("Elle est très ___.", "Она очень серьёзная. (sérieux)", "sérieuse"),
        G("C’est une ___ ville.", "Это красивый город. (beau)", "belle"),
        G("Ma mère est ___.", "Моя мама щедрая. (généreux)", "généreuse"),
        G("Mon amie est ___.", "Моя подруга рыжая. (roux)", "rousse"),
        C("Как правильно?", ["une femme intelligente", "une intelligente femme"]),
        C("Как правильно?", ["un petit chat", "un chat petit"]),
        L("Elle est heureuse.", ["Il est heureux.", "Elle est heureuse."], 1),
        M("Противоположности", [["jeune", "vieux"], ["heureux", "triste"], ["travailleur", "paresseux"], ["grand", "petit"]]),
        M("Характер", [["drôle", "смешной"], ["curieux", "любопытный"], ["gentil", "добрый"], ["calme", "спокойный"], ["généreux", "щедрый"]]),
        O("Собери фразу «Она очень добрая»", ["est", "Elle", "très", "gentille"], "elle est très gentille"),
        D("Il est jeune et sportif.", "il est jeune et sportif"),
        T("Она умная и весёлая.", "elle est intelligente et drôle"),
        T("Мой друг высокий блондин.", "mon ami est grand et blond"),
    ),
    "homework": hw("Опиши себя и подругу (или друга): внешность и характер. Следи за родом прилагательных. 6 предложений.",
                   "Je suis brune et mince. Je suis curieuse et un peu timide. Mon amie Léa est grande et blonde. Elle est drôle et très gentille. Elle est aussi sportive.", 25),
}

# ---------------------------------------------------------------- 15 октября
CONTENT["2026-10-15"] = {
    "topic": "Письмо: мой распорядок дня · повторение недели",
    "theory": [
        th("Как связать рассказ",
           "Чтобы текст звучал связно, добавь слова порядка: d’abord — сначала, ensuite / puis — затем, après — после, enfin — наконец.",
           exs=[["D’abord, je me lève. Ensuite, je prends un café.", "Сначала я встаю. Затем пью кофе."], ["Enfin, je me couche.", "Наконец, я ложусь спать."]]),
        th("Как часто",
           "toujours — всегда, souvent — часто, parfois / de temps en temps — иногда, ne … jamais — никогда. Обычно стоят после глагола: je lis souvent.",
           exs=[["Je fais souvent du sport.", "Я часто занимаюсь спортом."], ["Je ne bois jamais de café le soir.", "Я никогда не пью кофе вечером."]]),
        th("Время дня",
           "le matin — утром, l’après-midi — днём, le soir — вечером, la nuit — ночью. С артиклем — «обычно, каждый раз»: le matin, je cours.",
           exs=[["Le matin, je me douche.", "По утрам я принимаю душ."], ["Le soir, je lis.", "По вечерам я читаю."]]),
    ],
    "vocab": [
        w("d-abord", "d’abord", "сначала", "D’abord, je me lève.", "Сначала я встаю.", forms=["abord"]),
        w("ensuite", "ensuite", "затем", "Ensuite, je m’habille.", "Затем я одеваюсь."),
        w("enfin", "enfin", "наконец", "Enfin, je dors.", "Наконец я сплю."),
        w("souvent", "souvent", "часто", "Je lis souvent.", "Я часто читаю."),
        w("parfois", "parfois", "иногда", "Parfois, je cuisine.", "Иногда я готовлю."),
        w("de-temps", "de temps en temps", "время от времени", "Je vais au cinéma de temps en temps.", "Время от времени хожу в кино."),
        w("tous-les-jours", "tous les jours", "каждый день", "J’apprends le français tous les jours.", "Я учу французский каждый день."),
        w("matin", "le matin", "утро; утром", "Le matin, je cours.", "Утром я бегаю.", "m", ["matin"]),
        w("apres-midi", "l’après-midi", "день (после полудня)", "L’après-midi, je travaille.", "Днём я работаю.", "m"),
        w("soir", "le soir", "вечер; вечером", "Le soir, je me repose.", "Вечером я отдыхаю.", "m", ["soir"]),
        w("nuit", "la nuit", "ночь; ночью", "Bonne nuit !", "Спокойной ночи!", "f", ["nuit"]),
        w("week-end", "le week-end", "выходные", "Le week-end, je me promène.", "На выходных я гуляю.", "m"),
    ],
    "topics": [
        topic("t-texte", "Слова для связного рассказа",
              ("«сначала»", ["d’abord", "enfin", "après"]),
              ("«наконец»", ["enfin", "ensuite", "souvent"]),
              ("«иногда»", ["parfois", "toujours", "jamais"])),
    ],
    "exercises": ex(
        M("Порядок и частота", [["d’abord", "сначала"], ["ensuite", "затем"], ["enfin", "наконец"], ["souvent", "часто"], ["parfois", "иногда"]]),
        C("Куда поставить souvent: «Я часто читаю»", ["Je lis souvent.", "Je souvent lis.", "Souvent je lis pas."]),
        C("«Я никогда не пью кофе»", ["Je ne bois jamais de café.", "Je bois jamais café.", "Je ne jamais bois de café."]),
        G("___, je me lève. Ensuite, je me douche.", "Сначала я встаю. Затем принимаю душ.", "d'abord", "d’abord"),
        G("Le ___, je me couche à onze heures.", "Вечером я ложусь в одиннадцать.", "soir"),
        G("Je me ___ à sept heures.", "Я просыпаюсь в семь. (повторение)", "réveille"),
        G("Ma sœur joue ___ piano.", "Моя сестра играет на пианино. (повторение)", "du"),
        G("Elle est très ___.", "Она очень спортивная. (повторение)", "sportive"),
        C("___ amie Léa (моя)", ["mon", "ma"]),
        L("D’abord, je prends un café.", ["D’abord, je prends un café.", "Après, je prends un café.", "Enfin, je prends un café."]),
        O("Собери фразу «Утром я бегаю»", ["matin", "Le", "je", "cours"], "le matin je cours", "le matin, je cours"),
        O("Собери фразу «Затем я одеваюсь»", ["m’habille", "Ensuite", "je"], "ensuite je m'habille", "ensuite, je m'habille"),
        D("Le week-end, je me repose.", "le week-end je me repose"),
        D("Je fais du sport tous les jours.", "je fais du sport tous les jours"),
        T("Иногда я готовлю.", "parfois je cuisine", "je cuisine parfois", "de temps en temps je cuisine"),
        T("Наконец я сплю.", "enfin je dors"),
    ),
    "homework": hw("Главное задание дня: опиши свой распорядок дня — 10 предложений от утра до вечера. Используй возвратные глаголы и слова d’abord, ensuite, puis, après, enfin. Отправь на проверку.",
                   "Le matin, je me réveille à sept heures. D’abord, je me lève et je me douche. Ensuite, je prends un café. Puis je m’habille et je pars au travail. Le soir, je me repose. Enfin, je me couche à minuit.", 50),
}

# ---------------------------------------------------------------- 16 октября
CONTENT["2026-10-16"] = {
    "topic": "Время · дни, месяцы, болезни",
    "theory": [
        th("Который час?",
           "Quelle heure est-il ? — Il est… Всегда с il est и словом heure(s).",
           table=[["Il est une heure.", "1:00"], ["Il est deux heures dix.", "2:10"], ["Il est trois heures et quart.", "3:15"], ["Il est quatre heures et demie.", "4:30"], ["Il est cinq heures moins le quart.", "4:45"], ["Il est midi / minuit.", "12:00 дня / ночи"]]),
        th("Во сколько?",
           "À quelle heure ? — À huit heures. В официальной речи часто 24-часовой формат: à dix-neuf heures (19:00).",
           exs=[["À quelle heure tu commences ?", "Во сколько ты начинаешь?"], ["Le film commence à vingt heures.", "Фильм начинается в 20:00."]]),
        th("Дни и месяцы",
           "Пишутся с маленькой буквы. lundi — в понедельник (этот), le lundi — по понедельникам. Месяцы — с en: en octobre. Дата: le 16 octobre.",
           exs=[["Lundi, je travaille.", "В понедельник я работаю."], ["Le samedi, je me repose.", "По субботам я отдыхаю."], ["Mon anniversaire est en mai.", "Мой день рождения в мае."]]),
        th("Мне плохо",
           "avoir mal à + часть тела: j’ai mal à la tête, au ventre, à la gorge. Температура — j’ai de la fièvre. Я болею — je suis malade.",
           exs=[["J’ai mal à la tête.", "У меня болит голова."], ["Je suis malade, j’ai de la fièvre.", "Я болею, у меня температура."]]),
    ],
    "vocab": [
        w("lundi", "lundi", "понедельник", "Lundi, je travaille.", "В понедельник я работаю.", "m"),
        w("mardi", "mardi", "вторник", "Mardi, j’ai cours.", "Во вторник у меня занятия.", "m"),
        w("mercredi", "mercredi", "среда", "Mercredi, je fais du sport.", "В среду я занимаюсь спортом.", "m"),
        w("jeudi", "jeudi", "четверг", "À jeudi !", "До четверга!", "m"),
        w("vendredi", "vendredi", "пятница", "Vendredi soir, on sort.", "В пятницу вечером мы идём гулять.", "m"),
        w("samedi", "samedi", "суббота", "Le samedi, je me repose.", "По субботам я отдыхаю.", "m"),
        w("dimanche", "dimanche", "воскресенье", "Dimanche, c’est le repos.", "Воскресенье — отдых.", "m"),
        w("mois-1", "janvier · février · mars", "январь · февраль · март", "En mars, il fait froid.", "В марте холодно.", "m", ["janvier", "février", "mars"]),
        w("mois-2", "avril · mai · juin", "апрель · май · июнь", "Mon anniversaire est en mai.", "Мой день рождения в мае.", "m", ["avril", "mai", "juin"]),
        w("mois-3", "juillet · août · septembre", "июль · август · сентябрь", "En août, on part en vacances.", "В августе мы едем в отпуск.", "m", ["juillet", "août", "septembre"]),
        w("mois-4", "octobre · novembre · décembre", "октябрь · ноябрь · декабрь", "Nous sommes en octobre.", "Сейчас октябрь.", "m", ["octobre", "novembre", "décembre"]),
        w("semaine", "une semaine", "неделя", "Une fois par semaine.", "Раз в неделю.", "f"),
        w("mois", "un mois", "месяц", "Un mois de français.", "Месяц французского.", "m"),
        w("midi", "midi · minuit", "полдень · полночь", "Il est midi.", "Сейчас полдень.", "m", ["midi", "minuit"]),
        w("et-quart", "et quart · et demie · moins le quart", "с четвертью · с половиной · без четверти", "Il est deux heures et demie.", "Сейчас половина третьего.", None, ["quart", "demie", "demi"]),
        w("mal-a", "avoir mal à…", "болеть (о части тела)", "J’ai mal à la gorge.", "У меня болит горло.", None, ["mal"]),
        w("tete", "la tête", "голова", "J’ai mal à la tête.", "У меня болит голова.", "f"),
        w("ventre", "le ventre", "живот", "J’ai mal au ventre.", "У меня болит живот.", "m"),
        w("gorge", "la gorge", "горло", "Il a mal à la gorge.", "У него болит горло.", "f"),
        w("fievre", "la fièvre", "температура, жар", "J’ai de la fièvre.", "У меня температура.", "f"),
        w("malade", "malade", "больной", "Je suis malade.", "Я болею."),
        w("rhume", "un rhume", "насморк, простуда", "J’ai un rhume.", "У меня простуда.", "m"),
        w("grippe", "la grippe", "грипп", "Il a la grippe.", "У него грипп.", "f"),
        w("tousser", "tousser", "кашлять", "Je tousse beaucoup.", "Я сильно кашляю.", forms=["tousse", "tousses"]),
        w("pharmacie-m", "un médicament", "лекарство", "Je prends un médicament.", "Я принимаю лекарство.", "m", ["médicament", "médicaments"]),
    ],
    "topics": [
        topic("t-heure", "Который час",
              ("3:30", ["trois heures et demie", "trois heures et quart", "demi trois heures"]),
              ("7:45", ["huit heures moins le quart", "sept heures moins le quart", "sept heures et quart"]),
              ("12:00 днём", ["midi", "minuit", "douze heure"])),
        topic("t-mal", "Болезни",
              ("«У меня болит голова»", ["J’ai mal à la tête.", "Je suis mal à la tête.", "J’ai mal la tête."]),
              ("«У меня болит живот»", ["J’ai mal au ventre.", "J’ai mal à le ventre.", "J’ai mal du ventre."])),
    ],
    "exercises": ex(
        C("7:45 —", ["huit heures moins le quart", "sept heures moins le quart", "sept heures et quart"]),
        C("3:30 —", ["trois heures et demie", "trois heures et quart", "trois heures moins demie"]),
        C("12:00 дня —", ["midi", "minuit", "douze heures du soir"]),
        G("Il est deux heures et ___.", "Сейчас 2:30.", "demie"),
        G("J’ai mal ___ tête.", "У меня болит голова.", "à la"),
        G("J’ai mal ___ ventre.", "У меня болит живот.", "au"),
        G("Mon anniversaire est ___ mai.", "Мой день рождения в мае.", "en"),
        C("«По понедельникам» —", ["le lundi", "en lundi", "à lundi"]),
        L("Il est onze heures.", ["11:00", "7:00", "2:00"]),
        L("Il est six heures et quart.", ["6:15", "6:45", "5:45"]),
        M("Дни недели", [["lundi", "понедельник"], ["mercredi", "среда"], ["jeudi", "четверг"], ["vendredi", "пятница"], ["dimanche", "воскресенье"]]),
        M("Месяцы", [["janvier", "январь"], ["avril", "апрель"], ["juillet", "июль"], ["août", "август"], ["décembre", "декабрь"]]),
        O("Собери фразу «У меня болит горло»", ["mal", "J’", "gorge", "la", "à", "ai"], "j'ai mal à la gorge"),
        D("Il est midi et demi.", "il est midi et demi"),
        D("Je suis malade.", "je suis malade"),
        T("Который час?", "quelle heure est-il", "il est quelle heure"),
        T("В субботу я отдыхаю.", "samedi je me repose", "le samedi je me repose"),
        T("У меня температура.", "j'ai de la fièvre"),
    ),
    "homework": hw("Напиши свою неделю: что ты делаешь в каждый день недели и во сколько. Добавь предложение о том, когда твой день рождения, и одно — как ты себя чувствуешь сегодня.",
                   "Le lundi, je travaille de neuf heures à six heures. Le mercredi, je fais du yoga à sept heures. Le samedi, je me repose. Mon anniversaire est en mai. Aujourd’hui, j’ai mal à la tête.", 30),
}
