# -*- coding: utf-8 -*-
"""Неделя 3: 19–23 октября."""
from h import w, C, L, G, J, M, O, D, T, ex, th, topic, hw

CONTENT = {}

# ---------------------------------------------------------------- 19 октября
CONTENT["2026-10-19"] = {
    "topic": "Числа: количественные и порядковые",
    "theory": [
        th("0–20",
           "Эти числа надо просто выучить. 17, 18, 19 — это «десять-семь», «десять-восемь», «десять-девять».",
           table=[["0 zéro · 1 un · 2 deux · 3 trois", ""], ["4 quatre · 5 cinq · 6 six · 7 sept", ""], ["8 huit · 9 neuf · 10 dix", ""], ["11 onze · 12 douze · 13 treize", ""], ["14 quatorze · 15 quinze · 16 seize", ""], ["17 dix-sept · 18 dix-huit · 19 dix-neuf · 20 vingt", ""]]),
        th("Десятки до 69",
           "20 vingt, 30 trente, 40 quarante, 50 cinquante, 60 soixante. Единицы присоединяются через дефис: vingt-deux, trente-cinq. С единицей — через et: vingt et un, trente et un.",
           exs=[["vingt et un", "21"], ["trente-cinq", "35"], ["soixante-huit", "68"]]),
        th("70–99 — французская арифметика",
           "70 = 60 + 10 (soixante-dix), 80 = 4 × 20 (quatre-vingts), 90 = 4 × 20 + 10 (quatre-vingt-dix). Дальше прибавляем: 71 soixante et onze, 75 soixante-quinze, 81 quatre-vingt-un, 92 quatre-vingt-douze. В Бельгии и Швейцарии говорят septante и nonante.",
           exs=[["soixante-dix", "70"], ["soixante et onze", "71"], ["quatre-vingts", "80"], ["quatre-vingt-dix-neuf", "99"]]),
        th("100 и больше, порядковые",
           "100 cent, 200 deux cents, 250 deux cent cinquante, 1000 mille. Порядковые: + -ième: deuxième, troisième, dixième. Исключение — premier / première.",
           exs=[["deux cents", "200"], ["mille", "1000"], ["le premier jour", "первый день"], ["la troisième fois", "третий раз"]]),
    ],
    "vocab": [
        w("n-0-5", "zéro · un · deux · trois · quatre · cinq", "0 · 1 · 2 · 3 · 4 · 5", "", "", None, ["zéro", "trois", "quatre", "cinq"]),
        w("n-6-10", "six · sept · huit · neuf · dix", "6 · 7 · 8 · 9 · 10", "", "", None, ["six", "sept", "huit", "neuf", "dix"]),
        w("n-11-16", "onze · douze · treize · quatorze · quinze · seize", "11 · 12 · 13 · 14 · 15 · 16", "", "", None, ["onze", "douze", "treize", "quatorze", "quinze", "seize"]),
        w("n-17-19", "dix-sept · dix-huit · dix-neuf", "17 · 18 · 19"),
        w("n-20", "vingt", "20", "J’ai vingt ans.", "Мне 20 лет."),
        w("n-21", "vingt et un", "21"),
        w("n-30", "trente", "30", "Trente euros.", "Тридцать евро."),
        w("n-40", "quarante", "40"),
        w("n-50", "cinquante", "50"),
        w("n-60", "soixante", "60"),
        w("n-70", "soixante-dix", "70 (= 60 + 10)"),
        w("n-71", "soixante et onze", "71"),
        w("n-80", "quatre-vingts", "80 (= 4 × 20)"),
        w("n-81", "quatre-vingt-un", "81"),
        w("n-90", "quatre-vingt-dix", "90 (= 4 × 20 + 10)"),
        w("n-99", "quatre-vingt-dix-neuf", "99"),
        w("n-100", "cent", "100", "Cent pour cent !", "Сто процентов!"),
        w("n-200", "deux cents", "200"),
        w("n-1000", "mille", "1000", "Mille mercis !", "Тысяча благодарностей!"),
        w("o-2", "deuxième", "второй", "Le deuxième étage.", "Третий этаж (второй над первым).", forms=["deuxième"]),
        w("o-3", "troisième", "третий", "La troisième rue.", "Третья улица.", forms=["troisième"]),
        w("numero", "un numéro", "номер", "Quel est ton numéro ?", "Какой у тебя номер?", "m"),
        w("combien", "combien", "сколько", "Ça coûte combien ?", "Сколько это стоит?"),
    ],
    "topics": [
        topic("t-nombres", "Числа 70–99",
              ("70", ["soixante-dix", "septante-dix", "sept-dix"]),
              ("80", ["quatre-vingts", "huitante", "huit-dix"]),
              ("91", ["quatre-vingt-onze", "quatre-vingt-dix-un", "nonante-un"]),
              ("71", ["soixante et onze", "soixante-onze-un", "soixante-dix-un"])),
    ],
    "exercises": ex(
        L("soixante-dix", ["60", "70", "80"], 1, "Какое число прозвучало?"),
        L("quatre-vingt-douze", ["82", "92", "72"], 1, "Какое число прозвучало?"),
        L("seize", ["6", "16", "60"], 1, "Какое число прозвучало?"),
        L("quarante-cinq", ["45", "54", "14"], 0, "Какое число прозвучало?"),
        G("Soixante et ___ = 71", "Впиши словом.", "onze"),
        G("Quatre-___ = 80", "Впиши словом.", "vingts"),
        G("trente-cinq = ___", "Впиши цифрами.", "35"),
        G("quatre-vingt-dix-neuf = ___", "Впиши цифрами.", "99"),
        C("«третий» —", ["troisième", "trois", "troisième un"]),
        C("«первый день» —", ["le premier jour", "le unième jour", "le un jour"]),
        C("200 —", ["deux cents", "deux cent", "deux-cents un"]),
        M("Числа", [["douze", "12"], ["quinze", "15"], ["cinquante", "50"], ["soixante", "60"], ["mille", "1000"]]),
        O("Собери фразу «Мне двадцать два года»", ["ai", "J’", "vingt-deux", "ans"], "j'ai vingt-deux ans"),
        D("J’ai trente ans.", "j'ai trente ans", "j'ai 30 ans"),
        D("Ça coûte quatre-vingts euros.", "ça coûte quatre-vingts euros", "ça coûte 80 euros"),
        T("Мне тридцать лет.", "j'ai trente ans", "j'ai 30 ans"),
        T("Сколько это стоит?", "ça coûte combien", "combien ça coûte", "c'est combien"),
    ),
    "homework": hw("Напиши числами-словами: твой возраст, возраст трёх родных или друзей, номер дома и сколько стоит твой любимый кофе. Проверь 70–99 особенно внимательно.",
                   "J’ai vingt-huit ans. Ma mère a cinquante-six ans. Mon grand-père a quatre-vingt-deux ans. J’habite au numéro soixante-quinze. Mon café coûte trois euros.", 25),
}

# ---------------------------------------------------------------- 20 октября
CONTENT["2026-10-20"] = {
    "topic": "Множественное число · тело и одежда",
    "theory": [
        th("Обычно + s",
           "un livre → des livres, une robe → des robes. На слух s не слышно — множественное число слышно по артиклю: le [лё] / les [ле].",
           exs=[["un pull, des pulls", "свитер, свитеры"], ["une chaussure, des chaussures", "ботинок, обувь"]]),
        th("Особые окончания",
           "-eau, -eu → + x: un chapeau → des chapeaux, un cheveu → des cheveux. -al → -aux: un cheval → des chevaux, un journal → des journaux. На -s, -x, -z ничего не меняется: un bras → des bras, un nez → des nez.",
           exs=[["un chapeau, des chapeaux", "шляпа, шляпы"], ["un journal, des journaux", "газета, газеты"], ["un nez, des nez", "нос, носы"]]),
        th("Совсем неправильное",
           "un œil → des yeux (глаз → глаза). Прилагательные подчиняются тем же правилам: beau → beaux, national → nationaux.",
           exs=[["Elle a les yeux bleus.", "У неё голубые глаза."], ["de beaux cheveux", "красивые волосы"]]),
        th("Одежда: porter, mettre",
           "porter — носить (что на тебе): je porte une robe. mettre — надевать: je mets un manteau.",
           exs=[["Il porte un jean.", "На нём джинсы."], ["Je mets mes chaussures.", "Я надеваю обувь."]]),
    ],
    "vocab": [
        w("corps", "le corps", "тело", "Le corps humain.", "Человеческое тело.", "m"),
        w("tete-2", "le visage", "лицо", "Un joli visage.", "Красивое лицо.", "m", ["visage"]),
        w("yeux", "un œil / des yeux", "глаз / глаза", "Elle a les yeux verts.", "У неё зелёные глаза.", "m", ["œil", "yeux"]),
        w("nez", "le nez", "нос", "J’ai le nez qui coule.", "У меня течёт из носа.", "m"),
        w("bouche", "la bouche", "рот", "Ouvre la bouche.", "Открой рот.", "f"),
        w("oreille", "l’oreille", "ухо", "J’ai mal à l’oreille.", "У меня болит ухо.", "f", ["oreille", "oreilles"]),
        w("cheveux", "les cheveux", "волосы", "Elle a les cheveux longs.", "У неё длинные волосы.", "m", ["cheveu", "cheveux"]),
        w("dent", "une dent", "зуб", "Je me brosse les dents.", "Я чищу зубы.", "f", ["dents"]),
        w("bras", "le bras", "рука (вся)", "J’ai mal au bras.", "У меня болит рука.", "m"),
        w("jambe", "la jambe", "нога", "Il a de longues jambes.", "У него длинные ноги.", "f", ["jambes"]),
        w("pied", "le pied", "стопа; à pied — пешком", "Je vais au travail à pied.", "Я хожу на работу пешком.", "m", ["pieds"]),
        w("dos", "le dos", "спина", "J’ai mal au dos.", "У меня болит спина.", "m"),
        w("vetements", "les vêtements", "одежда", "J’achète des vêtements.", "Я покупаю одежду.", "m", ["vêtement", "vêtements"]),
        w("pantalon", "un pantalon", "брюки", "Un pantalon noir.", "Чёрные брюки.", "m"),
        w("jean", "un jean", "джинсы", "Il porte un jean.", "На нём джинсы.", "m"),
        w("robe", "une robe", "платье", "Une belle robe.", "Красивое платье.", "f", ["robes"]),
        w("jupe", "une jupe", "юбка", "Une jupe courte.", "Короткая юбка.", "f"),
        w("chemise", "une chemise", "рубашка", "Une chemise blanche.", "Белая рубашка.", "f"),
        w("tee-shirt", "un tee-shirt", "футболка", "Un tee-shirt rouge.", "Красная футболка.", "m"),
        w("pull", "un pull", "свитер", "Je mets un pull.", "Я надеваю свитер.", "m"),
        w("manteau", "un manteau", "пальто (мн. ч. manteaux)", "Il fait froid, prends ton manteau.", "Холодно, возьми пальто.", "m", ["manteaux"]),
        w("veste", "une veste", "куртка, пиджак", "Une veste en cuir.", "Кожаная куртка.", "f"),
        w("chaussures", "des chaussures", "обувь", "Des chaussures confortables.", "Удобная обувь.", "f", ["chaussure"]),
        w("chaussettes", "des chaussettes", "носки", "Des chaussettes chaudes.", "Тёплые носки.", "f", ["chaussette"]),
        w("chapeau", "un chapeau", "шляпа (мн. ч. chapeaux)", "Un grand chapeau.", "Большая шляпа.", "m", ["chapeaux"]),
        w("porter", "porter", "носить (одежду)", "Elle porte une robe.", "На ней платье.", forms=["porte", "portes", "portons", "portez", "portent"]),
    ],
    "topics": [
        topic("t-pluriel", "Множественное число",
              ("un chapeau →", ["des chapeaux", "des chapeaus", "des chapeau"]),
              ("un journal →", ["des journaux", "des journals", "des journauxs"]),
              ("un œil →", ["des yeux", "des œils", "des œux"]),
              ("un nez →", ["des nez", "des nezs", "des nezx"])),
    ],
    "exercises": ex(
        C("un chapeau →", ["des chapeaux", "des chapeaus"]),
        C("un cheval →", ["des chevaux", "des chevals"]),
        C("un œil →", ["des yeux", "des œils"]),
        C("un bras →", ["des bras", "des brass"]),
        G("J’achète deux ___.", "Я покупаю два свитера. (pull)", "pulls"),
        G("Elle a les ___ bleus.", "У неё голубые глаза.", "yeux"),
        G("Les ___ sont dans l’armoire.", "Пальто в шкафу. (manteau)", "manteaux"),
        G("J’ai mal au ___.", "У меня болит спина.", "dos"),
        G("Il ___ un jean.", "На нём джинсы. (porter)", "porte"),
        L("les cheveux", ["les chevaux", "les cheveux"], 1),
        M("Тело", [["la jambe", "нога"], ["le bras", "рука"], ["la bouche", "рот"], ["l’oreille", "ухо"], ["le nez", "нос"]]),
        M("Одежда", [["une jupe", "юбка"], ["une chemise", "рубашка"], ["des chaussettes", "носки"], ["une veste", "куртка"], ["un pull", "свитер"]]),
        O("Собери фразу «Она носит красивое платье»", ["porte", "Elle", "une", "robe", "belle"], "elle porte une belle robe"),
        D("Elle a les cheveux longs.", "elle a les cheveux longs"),
        D("Je mets mes chaussures.", "je mets mes chaussures"),
        T("У меня болит нога.", "j'ai mal à la jambe"),
        T("Я иду пешком.", "je vais à pied", "je marche"),
    ),
    "homework": hw("Опиши, что на тебе надето сегодня и что ты обычно носишь на работу/учёбу. Добавь 2 предложения о внешности: глаза, волосы.",
                   "Aujourd’hui, je porte un jean et un pull gris. Au travail, je porte souvent une chemise. En hiver, je mets un manteau. J’ai les yeux verts et les cheveux longs.", 25),
}

# ---------------------------------------------------------------- 21 октября
CONTENT["2026-10-21"] = {
    "topic": "Futur proche · семья и дом",
    "theory": [
        th("Ближайшее будущее: aller + инфинитив",
           "Самый простой способ говорить о будущем: форма aller + глагол в инфинитиве. Je vais manger — я собираюсь поесть / я поем.",
           table=[["je vais partir", "я уеду"], ["tu vas voir", "ты увидишь"], ["il va pleuvoir", "будет дождь"], ["nous allons dîner", "мы поужинаем"], ["vous allez aimer", "вам понравится"], ["ils vont arriver", "они приедут"]]),
        th("Отрицание",
           "ne … pas обнимают aller: je ne vais pas travailler demain.",
           exs=[["Je ne vais pas sortir ce soir.", "Сегодня вечером я не пойду гулять."]]),
        th("Слова-маркеры будущего",
           "demain — завтра, ce soir — сегодня вечером, ce week-end — в эти выходные, la semaine prochaine — на следующей неделе, bientôt — скоро.",
           exs=[["Demain, je vais voir ma mère.", "Завтра я увижу маму."], ["La semaine prochaine, nous allons partir.", "На следующей неделе мы уедем."]]),
    ],
    "vocab": [
        w("famille", "la famille", "семья", "Ma famille est grande.", "У меня большая семья.", "f"),
        w("parents", "les parents", "родители", "Mes parents habitent à Kazan.", "Мои родители живут в Казани.", "m"),
        w("pere", "le père · papa", "отец · папа", "Mon père est médecin.", "Мой отец врач.", "m", ["père", "papa"]),
        w("mere", "la mère · maman", "мать · мама", "Ma mère est gentille.", "Моя мама добрая.", "f", ["mère", "maman"]),
        w("frere", "le frère", "брат", "J’ai un frère.", "У меня есть брат.", "m", ["frère", "frères"]),
        w("soeur", "la sœur", "сестра", "Ma sœur est petite.", "Моя сестра маленькая.", "f", ["sœur", "sœurs"]),
        w("fils", "le fils", "сын", "Leur fils a dix ans.", "Их сыну десять лет.", "m"),
        w("fille", "la fille", "дочь; девочка", "Leur fille est étudiante.", "Их дочь студентка.", "f", ["filles"]),
        w("grands-parents", "le grand-père · la grand-mère", "дедушка · бабушка", "Ma grand-mère fait des gâteaux.", "Бабушка печёт пироги.", None, ["grand-père", "grand-mère", "grands-parents"]),
        w("oncle", "l’oncle · la tante", "дядя · тётя", "Mon oncle habite en France.", "Мой дядя живёт во Франции.", None, ["oncle", "tante"]),
        w("cousin", "le cousin · la cousine", "двоюродный брат · сестра", "Ma cousine a vingt ans.", "Моей кузине двадцать лет.", None, ["cousin", "cousine"]),
        w("mari", "le mari", "муж", "Son mari est gentil.", "Её муж добрый.", "m"),
        w("maison", "la maison", "дом; à la maison — дома", "Je suis à la maison.", "Я дома.", "f", ["maison", "maisons"]),
        w("appartement", "un appartement", "квартира", "Un appartement au centre.", "Квартира в центре.", "m"),
        w("cuisine", "la cuisine", "кухня", "On mange dans la cuisine.", "Мы едим на кухне.", "f"),
        w("chambre", "la chambre", "спальня, комната", "Ma chambre est petite.", "Моя комната маленькая.", "f"),
        w("salon", "le salon", "гостиная", "On regarde la télé dans le salon.", "Смотрим телевизор в гостиной.", "m"),
        w("salle-de-bains", "la salle de bains", "ванная", "La salle de bains est à droite.", "Ванная справа.", "f"),
        w("toilettes", "les toilettes", "туалет", "Où sont les toilettes ?", "Где туалет?", "f"),
        w("jardin", "le jardin", "сад", "Les enfants jouent dans le jardin.", "Дети играют в саду.", "m"),
        w("balcon", "le balcon", "балкон", "Je bois un café sur le balcon.", "Я пью кофе на балконе.", "m"),
        w("fenetre", "la fenêtre", "окно", "J’ouvre la fenêtre.", "Я открываю окно.", "f"),
        w("porte", "la porte", "дверь", "Ferme la porte !", "Закрой дверь!", "f"),
        w("demain", "demain", "завтра", "À demain !", "До завтра!"),
        w("prochain", "prochain / prochaine", "следующий", "La semaine prochaine.", "На следующей неделе.", forms=["prochain", "prochaine"]),
        w("bientot-2", "ce soir", "сегодня вечером", "Ce soir, on va au cinéma.", "Сегодня вечером идём в кино."),
    ],
    "topics": [
        topic("t-futur-proche", "Futur proche",
              ("«Я поеду в Париж»", ["Je vais aller à Paris.", "Je vais à aller Paris.", "Je allerai Paris."]),
              ("«Они приедут завтра»", ["Ils vont arriver demain.", "Ils vont arrivent demain.", "Ils va arriver demain."]),
              ("«Я не буду работать»", ["Je ne vais pas travailler.", "Je vais ne pas travailler.", "Je ne vais travailler pas."])),
    ],
    "exercises": ex(
        J("aller + dîner", [["je", "vais dîner"], ["tu", "vas dîner"], ["il", "va dîner"], ["nous", "allons dîner"], ["vous", "allez dîner"], ["ils", "vont dîner"]], q="Futur proche: «поужинать»"),
        G("Demain, je ___ voir ma mère.", "Завтра я увижу маму.", "vais"),
        G("Ce soir, nous ___ regarder un film.", "Сегодня вечером мы посмотрим фильм.", "allons"),
        G("Il ___ pleuvoir.", "Будет дождь.", "va"),
        G("Mes parents vont ___ la semaine prochaine.", "Мои родители приедут на следующей неделе. (arriver)", "arriver"),
        C("«Я не пойду гулять»", ["Je ne vais pas sortir.", "Je vais ne pas sortir.", "Je ne vais sortir pas."]),
        C("Где сейчас мы? «Nous mangeons dans la cuisine»", ["на кухне", "в спальне", "в саду"]),
        L("Ils vont arriver demain.", ["Il va arriver demain.", "Ils vont arriver demain.", "Ils vont partir demain."], 1),
        M("Семья", [["le père", "отец"], ["la sœur", "сестра"], ["le fils", "сын"], ["la tante", "тётя"], ["le mari", "муж"]]),
        M("Дом", [["la chambre", "спальня"], ["le salon", "гостиная"], ["la salle de bains", "ванная"], ["la fenêtre", "окно"], ["la porte", "дверь"]]),
        O("Собери фразу «Завтра я поеду в Лион»", ["vais", "Demain", "je", "aller", "à", "Lyon"], "demain je vais aller à lyon", "demain, je vais aller à lyon"),
        O("Собери фразу «Мы не будем работать»", ["n’allons", "Nous", "pas", "travailler"], "nous n'allons pas travailler"),
        D("Ma grand-mère va faire un gâteau.", "ma grand-mère va faire un gâteau"),
        D("J’habite dans un petit appartement.", "j'habite dans un petit appartement"),
        T("Сегодня вечером я буду читать.", "ce soir je vais lire"),
        T("У меня есть брат и сестра.", "j'ai un frère et une sœur"),
        T("Моя комната маленькая.", "ma chambre est petite"),
    ),
    "homework": hw("Две части: 1) опиши свою семью и дом/квартиру (3–4 предложения); 2) напиши планы на эти выходные с futur proche (3–4 предложения).",
                   "Ma famille est petite. J’ai une sœur. Nous habitons dans un appartement avec un balcon. Ce week-end, je vais voir mes parents. Samedi, nous allons faire une randonnée. Dimanche, je vais me reposer.", 35),
}

# ---------------------------------------------------------------- 22 октября
CONTENT["2026-10-22"] = {
    "topic": "Impératif · город, транспорт, деньги",
    "theory": [
        th("Повелительное наклонение",
           "Берём форму настоящего времени tu, nous, vous и убираем местоимение: tu prends → Prends ! nous allons → Allons ! vous écoutez → Écoutez !",
           exs=[["Prends le bus !", "Садись на автобус!"], ["Allons au cinéma !", "Пойдём в кино!"], ["Écoutez bien.", "Слушайте внимательно."]]),
        th("У глаголов на -er в форме tu пропадает s",
           "tu parles → Parle ! tu regardes → Regarde ! Так же aller: tu vas → Va !",
           exs=[["Regarde !", "Смотри!"], ["Va à la gare !", "Иди на вокзал!"]]),
        th("Неправильные и отрицание",
           "être → sois, soyons, soyez; avoir → aie, ayons, ayez. Отрицание: Ne parle pas ! Возвратные: Lève-toi ! Ne te lève pas !",
           exs=[["Sois gentil !", "Будь добр!"], ["N’ayez pas peur.", "Не бойтесь."], ["Dépêche-toi !", "Поторопись!"]]),
        th("Как объяснить дорогу",
           "Allez tout droit — идите прямо, tournez à gauche / à droite — поверните налево / направо, prenez la deuxième rue — сверните на вторую улицу.",
           exs=[["Tournez à droite, puis allez tout droit.", "Поверните направо, потом идите прямо."]]),
    ],
    "vocab": [
        w("rue", "la rue", "улица", "J’habite dans cette rue.", "Я живу на этой улице.", "f"),
        w("place", "la place", "площадь; место", "La place de la Concorde.", "Площадь Согласия.", "f"),
        w("quartier", "le quartier", "район", "Un quartier calme.", "Спокойный район.", "m"),
        w("gare", "la gare", "вокзал", "Où est la gare ?", "Где вокзал?", "f"),
        w("aeroport", "l’aéroport", "аэропорт", "Je vais à l’aéroport.", "Я еду в аэропорт.", "m", ["aéroport"]),
        w("banque", "la banque", "банк", "La banque est fermée.", "Банк закрыт.", "f"),
        w("poste", "la poste", "почта", "Je vais à la poste.", "Я иду на почту.", "f"),
        w("magasin", "le magasin", "магазин", "Un magasin de vêtements.", "Магазин одежды.", "m", ["magasins"]),
        w("supermarche", "le supermarché", "супермаркет", "On va au supermarché.", "Идём в супермаркет.", "m"),
        w("pharmacie", "la pharmacie", "аптека", "La pharmacie est à côté.", "Аптека рядом.", "f"),
        w("hopital", "l’hôpital", "больница", "Elle travaille à l’hôpital.", "Она работает в больнице.", "m", ["hôpital"]),
        w("boulangerie", "la boulangerie", "булочная", "J’achète du pain à la boulangerie.", "Я покупаю хлеб в булочной.", "f"),
        w("metro", "le métro", "метро", "Je prends le métro.", "Я еду на метро.", "m"),
        w("bus", "le bus", "автобус", "Le bus arrive.", "Автобус подъезжает.", "m"),
        w("train", "le train", "поезд", "Le train pour Bruxelles.", "Поезд в Брюссель.", "m"),
        w("voiture", "la voiture", "машина", "J’ai une petite voiture.", "У меня маленькая машина.", "f"),
        w("taxi", "le taxi", "такси", "On prend un taxi ?", "Возьмём такси?", "m"),
        w("ticket", "un ticket / un billet", "билет", "Un billet de train.", "Билет на поезд.", "m", ["ticket", "billet", "billets"]),
        w("argent", "l’argent", "деньги", "Je n’ai pas d’argent.", "У меня нет денег.", "m", ["argent"]),
        w("carte", "la carte bancaire", "банковская карта", "Je paie par carte.", "Я плачу картой.", "f", ["carte"]),
        w("euro", "un euro", "евро", "Ça fait dix euros.", "С вас десять евро.", "m", ["euros"]),
        w("prix", "le prix", "цена", "Quel est le prix ?", "Какая цена?", "m"),
        w("cout", "coûter", "стоить", "Ça coûte combien ?", "Сколько это стоит?", forms=["coûte", "coûtent"]),
        w("gauche", "à gauche · à droite", "налево/слева · направо/справа", "Tournez à gauche.", "Поверните налево.", None, ["gauche", "droite"]),
        w("tout-droit", "tout droit", "прямо", "Allez tout droit.", "Идите прямо."),
        w("tourner", "tourner", "поворачивать", "Tourne à droite !", "Поверни направо!", forms=["tourne", "tournez"]),
    ],
    "topics": [
        topic("t-imperatif", "Impératif",
              ("tu regardes → ", ["Regarde !", "Regardes !", "Tu regarde !"]),
              ("vous prenez → ", ["Prenez !", "Prendez !", "Vous prenez !"]),
              ("être (tu) → ", ["Sois !", "Es !", "Soit !"]),
              ("«Не бойтесь»", ["N’ayez pas peur.", "Ne avez pas peur.", "N’ayez peur pas."])),
    ],
    "exercises": ex(
        C("tu regardes →", ["Regarde !", "Regardes !"]),
        C("vous prenez →", ["Prenez !", "Prendez !"]),
        C("nous allons →", ["Allons !", "Allez !"]),
        C("être (tu) →", ["Sois !", "Es !"]),
        G("___ le bus !", "Садись на автобус! (prendre, tu)", "prends"),
        G("___ à gauche !", "Поверните налево! (tourner, vous)", "tournez"),
        G("Ne ___ pas !", "Не говори! (parler, tu)", "parle"),
        G("___-toi !", "Поторопись! (se dépêcher)", "dépêche"),
        G("Allez tout ___ .", "Идите прямо.", "droit"),
        L("Tournez à droite.", ["Tournez à droite.", "Tournez à gauche.", "Allez tout droit."]),
        M("Город", [["la gare", "вокзал"], ["la pharmacie", "аптека"], ["la boulangerie", "булочная"], ["la banque", "банк"], ["le quartier", "район"]]),
        M("Транспорт и деньги", [["la voiture", "машина"], ["le billet", "билет"], ["l’argent", "деньги"], ["le prix", "цена"], ["la carte bancaire", "банковская карта"]]),
        O("Собери фразу «Идите прямо, потом поверните направо»", ["tout", "Allez", "droit", "puis", "tournez", "à", "droite"], "allez tout droit puis tournez à droite", "allez tout droit, puis tournez à droite"),
        D("Prenez la deuxième rue à gauche.", "prenez la deuxième rue à gauche"),
        D("Je paie par carte.", "je paie par carte"),
        T("Где вокзал?", "où est la gare"),
        T("Сколько стоит билет?", "combien coûte le billet", "le billet coûte combien", "c'est combien le billet"),
    ),
    "homework": hw("Объясни другу дорогу от твоего дома до ближайшего кафе или магазина — 5–6 команд в impératif (allez / tournez / prenez…). Добавь, на чём ты обычно ездишь по городу.",
                   "Sors de la maison. Tourne à droite. Va tout droit jusqu’à la pharmacie. Puis prends la deuxième rue à gauche. Le café est à côté de la banque. Moi, je prends souvent le métro.", 30),
}

# ---------------------------------------------------------------- 23 октября
CONTENT["2026-10-23"] = {
    "topic": "Passé récent · описание человека",
    "theory": [
        th("Только что: venir de + инфинитив",
           "Чтобы сказать «я только что…», берём venir в настоящем времени + de + инфинитив: je viens de manger — я только что поела. Перед гласной — d’: il vient d’arriver.",
           table=[["je viens de finir", "я только что закончила"], ["tu viens de voir", "ты только что видел"], ["il vient d’arriver", "он только что приехал"], ["nous venons de manger", "мы только что поели"], ["vous venez de lire", "вы только что прочитали"], ["ils viennent de partir", "они только что ушли"]]),
        th("Три времени одного глагола",
           "Теперь ты умеешь: je mange (сейчас), je vais manger (скоро), je viens de manger (только что).",
           exs=[["Je mange.", "Я ем."], ["Je vais manger.", "Я поем."], ["Je viens de manger.", "Я только что поела."]]),
        th("Как описать человека",
           "Il / Elle est + прилагательное (характер, рост): elle est grande et drôle. Il / Elle a + части тела: il a les yeux bleus, les cheveux courts. Il / Elle porte + одежда: elle porte des lunettes.",
           exs=[["Elle a les cheveux longs et bruns.", "У неё длинные тёмные волосы."], ["Il porte des lunettes.", "Он носит очки."], ["Il a l’air sympa.", "Он выглядит приятным."]]),
    ],
    "vocab": [
        w("venir-de", "venir de + infinitif", "только что (сделать)", "Je viens de rentrer.", "Я только что вернулась."),
        w("lunettes", "des lunettes", "очки", "Elle porte des lunettes.", "Она носит очки.", "f", ["lunettes"]),
        w("barbe", "une barbe", "борода", "Il a une barbe.", "У него борода.", "f"),
        w("moustache", "une moustache", "усы", "Mon grand-père a une moustache.", "У дедушки усы.", "f"),
        w("long", "long / longue", "длинный", "Les cheveux longs.", "Длинные волосы.", forms=["long", "longue", "longs", "longues"]),
        w("court", "court / courte", "короткий", "Les cheveux courts.", "Короткие волосы.", forms=["court", "courte", "courts", "courtes"]),
        w("couleurs-1", "bleu · vert · marron", "голубой · зелёный · карий", "Il a les yeux marron.", "У него карие глаза.", None, ["bleu", "bleus", "vert", "verts", "marron"]),
        w("couleurs-2", "noir · blanc · gris", "чёрный · белый · серый", "Un pull gris.", "Серый свитер.", None, ["noir", "noirs", "blanc", "blanche", "gris"]),
        w("avoir-l-air", "avoir l’air", "выглядеть (каким-то)", "Tu as l’air fatiguée.", "Ты выглядишь уставшей.", None, ["air"]),
        w("mesurer", "mesurer", "иметь рост", "Il mesure un mètre quatre-vingts.", "Его рост 1,80.", forms=["mesure"]),
        w("ressembler", "ressembler à", "быть похожим на", "Tu ressembles à ta mère.", "Ты похожа на маму.", forms=["ressemble", "ressembles"]),
    ],
    "topics": [
        topic("t-passe-recent", "Passé récent",
              ("«Я только что поела»", ["Je viens de manger.", "Je vais manger.", "Je viens manger."]),
              ("«Он только что приехал»", ["Il vient d’arriver.", "Il va arriver.", "Il vient de arriver."]),
              ("ils (venir de partir)", ["Ils viennent de partir.", "Ils venent de partir.", "Ils vient de partir."])),
    ],
    "exercises": ex(
        J("venir de finir", [["je", "viens de finir"], ["tu", "viens de finir"], ["elle", "vient de finir"], ["nous", "venons de finir"], ["vous", "venez de finir"], ["ils", "viennent de finir"]], q="Passé récent: «только что закончить»"),
        G("Je ___ de manger.", "Я только что поела.", "viens"),
        G("Il vient ___ arriver.", "Он только что приехал.", "d'", "d’"),
        G("Nous ___ de voir un film.", "Мы только что посмотрели фильм.", "venons"),
        C("Какое время? «Je vais partir»", ["будущее: я уеду", "прошлое: я только что уехала", "настоящее: я уезжаю"]),
        C("Какое время? «Je viens de partir»", ["я только что уехала", "я уеду", "я уезжаю"]),
        G("Elle ___ les cheveux longs.", "У неё длинные волосы.", "a"),
        G("Il ___ des lunettes.", "Он носит очки.", "porte"),
        C("«Ты похожа на маму»", ["Tu ressembles à ta mère.", "Tu ressembles ta mère.", "Tu es ressemble à ta mère."]),
        L("Ils viennent de partir.", ["Ils viennent de partir.", "Ils vont partir.", "Il vient de partir."]),
        M("Внешность", [["une barbe", "борода"], ["des lunettes", "очки"], ["court", "короткий"], ["long", "длинный"], ["marron", "карий"]]),
        O("Собери фразу «Я только что закончила работу»", ["viens", "Je", "finir", "de", "le", "travail"], "je viens de finir le travail"),
        D("Il a les yeux bleus et une barbe.", "il a les yeux bleus et une barbe"),
        D("Tu as l’air fatiguée.", "tu as l'air fatiguée"),
        T("Мы только что поели.", "nous venons de manger", "on vient de manger"),
        T("У него короткие волосы.", "il a les cheveux courts"),
    ),
    "homework": hw("Главное письмо дня: опиши человека (друга, родственника или героя сериала) — 10–12 предложений: кто он, как выглядит, что носит, какой у него характер, что он только что сделал или скоро сделает.",
                   "Mon ami s’appelle Marc. Il a trente ans. Il est grand et mince. Il a les cheveux courts et les yeux marron. Il porte souvent un jean et des lunettes. Il est drôle et très gentil. Il vient de trouver un nouveau travail. Le week-end prochain, il va partir en Italie.", 50),
}
