# -*- coding: utf-8 -*-
"""Неделя 4 (разгрузка): 26–29 октября."""
from h import w, C, L, G, J, M, O, D, T, ex, th, topic, hw

CONTENT = {}

# ---------------------------------------------------------------- 26 октября
CONTENT["2026-10-26"] = {
    "topic": "Passé composé с avoir · погода",
    "theory": [
        th("Прошедшее время: avoir + participe passé",
           "Passé composé — главное прошедшее время для событий: «сделала, посмотрела». Берём avoir в настоящем времени и причастие смыслового глагола.",
           table=[["j’ai mangé", "я поела"], ["tu as regardé", "ты посмотрел"], ["il a fini", "он закончил"], ["nous avons parlé", "мы поговорили"], ["vous avez choisi", "вы выбрали"], ["ils ont attendu", "они подождали"]]),
        th("Как образовать причастие",
           "-er → -é (parler → parlé), -ir (2-я группа) → -i (finir → fini), многие на -re → -u (attendre → attendu, répondre → répondu).",
           exs=[["J’ai travaillé hier.", "Я работала вчера."], ["Elle a choisi une robe.", "Она выбрала платье."], ["Nous avons attendu le bus.", "Мы ждали автобус."]]),
        th("Отрицание и маркеры времени",
           "ne … pas обнимают avoir: je n’ai pas mangé. Слова прошлого: hier — вчера, la semaine dernière — на прошлой неделе, il y a deux jours — два дня назад.",
           exs=[["Je n’ai pas regardé le film.", "Я не посмотрела фильм."], ["Il y a deux jours, j’ai parlé avec ma mère.", "Два дня назад я говорила с мамой."]]),
        th("Погода",
           "Il fait beau / chaud / froid — хорошая погода / жарко / холодно. Il pleut — идёт дождь, il neige — идёт снег. Il y a du vent / du soleil — ветрено / солнечно.",
           exs=[["Aujourd’hui, il fait froid.", "Сегодня холодно."], ["Hier, il a plu.", "Вчера шёл дождь."]]),
    ],
    "vocab": [
        w("meteo", "la météo", "прогноз погоды", "La météo annonce de la pluie.", "Прогноз обещает дождь.", "f"),
        w("il-fait-beau", "il fait beau", "хорошая погода", "Il fait beau aujourd’hui.", "Сегодня хорошая погода.", None, ["fait"]),
        w("chaud", "il fait chaud", "жарко", "En août, il fait chaud.", "В августе жарко.", None, ["chaud"]),
        w("froid", "il fait froid", "холодно", "Il fait froid en hiver.", "Зимой холодно.", None, ["froid"]),
        w("pleut", "il pleut", "идёт дождь", "Il pleut, prends un parapluie.", "Идёт дождь, возьми зонт.", None, ["pleut", "plu"]),
        w("neige", "il neige · la neige", "идёт снег · снег", "Il neige à Moscou.", "В Москве идёт снег.", None, ["neige"]),
        w("vent", "il y a du vent", "ветрено", "Il y a du vent sur la plage.", "На пляже ветрено.", None, ["vent"]),
        w("soleil", "le soleil", "солнце", "Il y a du soleil.", "Солнечно.", "m"),
        w("nuage", "un nuage", "облако", "Il y a des nuages.", "Облачно.", "m", ["nuages"]),
        w("pluie", "la pluie", "дождь", "J’aime la pluie.", "Я люблю дождь.", "f"),
        w("orage", "un orage", "гроза", "Un gros orage.", "Сильная гроза.", "m"),
        w("degres", "les degrés", "градусы", "Il fait vingt degrés.", "Двадцать градусов.", "m", ["degré", "degrés"]),
        w("parapluie", "un parapluie", "зонт", "J’ai oublié mon parapluie.", "Я забыла зонт.", "m"),
        w("hier", "hier", "вчера", "Hier, j’ai travaillé.", "Вчера я работала."),
        w("il-y-a-temps", "il y a + срок", "(столько-то) назад", "Il y a une semaine.", "Неделю назад."),
        w("dernier-2", "la semaine dernière", "на прошлой неделе", "La semaine dernière, il a plu.", "На прошлой неделе шёл дождь."),
    ],
    "topics": [
        topic("t-pc-avoir", "Passé composé с avoir",
              ("parler →", ["j’ai parlé", "je suis parlé", "j’ai parlu"]),
              ("finir →", ["j’ai fini", "j’ai finé", "j’ai finu"]),
              ("attendre →", ["j’ai attendu", "j’ai attendé", "j’ai attendi"]),
              ("«Я не поела»", ["Je n’ai pas mangé.", "Je n’ai mangé pas.", "Je ne pas ai mangé."])),
        topic("t-meteo", "Погода",
              ("«Холодно»", ["Il fait froid.", "Il est froid.", "C’est froid temps."]),
              ("«Идёт дождь»", ["Il pleut.", "Il fait pluie.", "Il est pluie."])),
    ],
    "exercises": ex(
        J("manger (passé composé)", [["j’", "ai mangé"], ["tu", "as mangé"], ["il", "a mangé"], ["nous", "avons mangé"], ["vous", "avez mangé"], ["ils", "ont mangé"]], q="Passé composé: «поесть»"),
        G("Hier, j’ai ___ avec ma sœur.", "Вчера я говорила с сестрой. (parler)", "parlé"),
        G("Nous avons ___ le travail.", "Мы закончили работу. (finir)", "fini"),
        G("Ils ont ___ le bus.", "Они ждали автобус. (attendre)", "attendu"),
        G("Tu ___ regardé le film ?", "Ты посмотрел фильм?", "as"),
        G("Je n’___ pas mangé.", "Я не поела.", "ai"),
        C("choisir → причастие", ["choisi", "choisé", "choisu"]),
        C("répondre → причастие", ["répondu", "répondé", "répondi"]),
        C("«Сегодня хорошая погода»", ["Il fait beau.", "Il est beau.", "C’est beau temps."]),
        L("Hier, il a plu.", ["Hier, il a plu.", "Il pleut aujourd’hui.", "Il fait beau."]),
        M("Погода", [["il pleut", "идёт дождь"], ["il neige", "идёт снег"], ["il fait chaud", "жарко"], ["un nuage", "облако"], ["un orage", "гроза"]]),
        O("Собери фразу «Вчера я работала»", ["ai", "Hier", "j’", "travaillé"], "hier j'ai travaillé", "hier, j'ai travaillé"),
        D("La semaine dernière, il a fait froid.", "la semaine dernière il a fait froid"),
        D("Il fait vingt degrés.", "il fait vingt degrés", "il fait 20 degrés"),
        T("Мы посмотрели фильм.", "nous avons regardé le film", "on a regardé le film", "nous avons regardé un film"),
        T("Сегодня холодно.", "aujourd'hui il fait froid", "il fait froid aujourd'hui"),
    ),
    "homework": hw("Напиши, что ты делала вчера (4–5 предложений в passé composé с avoir: j’ai mangé, j’ai regardé, j’ai fini…) и какая была погода.",
                   "Hier, il a fait froid. Le matin, j’ai travaillé. À midi, j’ai mangé avec une amie. Le soir, j’ai regardé un film et j’ai écouté un podcast.", 20),
}

# ---------------------------------------------------------------- 27 октября
CONTENT["2026-10-27"] = {
    "topic": "Неправильные причастия",
    "theory": [
        th("Причастия, которые надо выучить",
           "У частых неправильных глаголов причастие особое. Учи их парами «инфинитив — причастие».",
           table=[["être → été", "avoir → eu"], ["faire → fait", "dire → dit"], ["prendre → pris", "mettre → mis"], ["voir → vu", "lire → lu"], ["boire → bu", "écrire → écrit"], ["pouvoir → pu", "vouloir → voulu"], ["devoir → dû", "savoir → su"], ["ouvrir → ouvert", "vivre → vécu"]]),
        th("Семейства запоминаются вместе",
           "prendre → pris, значит и comprendre → compris, apprendre → appris. mettre → mis, promettre → promis.",
           exs=[["J’ai compris.", "Я поняла."], ["Elle a appris le français.", "Она выучила французский."]]),
        th("В разговоре",
           "Эти формы ты будешь слышать постоянно: j’ai fait, j’ai vu, j’ai pris, j’ai dit.",
           exs=[["Qu’est-ce que tu as fait ce week-end ?", "Что ты делала на выходных?"], ["J’ai vu un bon film.", "Я посмотрела хороший фильм."], ["Il a pris le train.", "Он поехал на поезде."]]),
    ],
    "vocab": [
        {"id": "p-" + a, "fr": b, "ru": c_, "g": None, "ex": d_, "exRu": e_, "forms": [f_]} for (a, b, c_, d_, e_, f_) in [
            ("ete", "être → été", "был(а)", "J’ai été malade.", "Я болела.", "été"),
            ("eu", "avoir → eu", "имел(а)", "J’ai eu de la chance.", "Мне повезло.", "eu"),
            ("fait", "faire → fait", "сделал(а)", "J’ai fait du sport.", "Я занималась спортом.", "fait"),
            ("dit", "dire → dit", "сказал(а)", "Il a dit bonjour.", "Он сказал «здравствуйте».", "dit"),
            ("pris", "prendre → pris", "взял(а)", "J’ai pris le métro.", "Я поехала на метро.", "pris"),
            ("mis", "mettre → mis", "положил(а); надел(а)", "J’ai mis un pull.", "Я надела свитер.", "mis"),
            ("vu", "voir → vu", "увидел(а)", "Tu as vu ce film ?", "Ты видела этот фильм?", "vu"),
            ("lu", "lire → lu", "прочитал(а)", "J’ai lu un livre.", "Я прочитала книгу.", "lu"),
            ("bu", "boire → bu", "выпил(а)", "J’ai bu un café.", "Я выпила кофе.", "bu"),
            ("ecrit", "écrire → écrit", "написал(а)", "Elle a écrit un message.", "Она написала сообщение.", "écrit"),
            ("pu", "pouvoir → pu", "смог(ла)", "Je n’ai pas pu venir.", "Я не смогла прийти.", "pu"),
            ("voulu", "vouloir → voulu", "захотел(а)", "Il a voulu partir.", "Он захотел уйти.", "voulu"),
            ("du", "devoir → dû", "был(а) должен(на)", "J’ai dû travailler.", "Мне пришлось работать.", "dû"),
            ("su", "savoir → su", "узнал(а)", "J’ai su la nouvelle.", "Я узнала новость.", "su"),
            ("connu", "connaître → connu", "знал(а); познакомился(ась)", "J’ai connu Paul à Paris.", "Я познакомилась с Полем в Париже.", "connu"),
            ("recu", "recevoir → reçu", "получил(а)", "J’ai reçu ton message.", "Я получила твоё сообщение.", "reçu"),
            ("ouvert", "ouvrir → ouvert", "открыл(а)", "J’ai ouvert la fenêtre.", "Я открыла окно.", "ouvert"),
            ("vecu", "vivre → vécu", "прожил(а)", "J’ai vécu à Kazan.", "Я жила в Казани.", "vécu"),
            ("compris", "comprendre → compris", "понял(а)", "Tu as compris ?", "Ты поняла?", "compris"),
            ("appris", "apprendre → appris", "выучил(а)", "J’ai appris dix mots.", "Я выучила десять слов.", "appris"),
        ]
    ],
    "topics": [
        topic("t-pp-irreg", "Неправильные причастия",
              ("faire →", ["fait", "faisé", "fai"]),
              ("prendre →", ["pris", "prendu", "prené"]),
              ("voir →", ["vu", "voiré", "vi"]),
              ("boire →", ["bu", "boiré", "bois"])),
    ],
    "exercises": ex(
        M("Причастия", [["faire", "fait"], ["prendre", "pris"], ["voir", "vu"], ["lire", "lu"], ["boire", "bu"]]),
        M("Причастия", [["écrire", "écrit"], ["mettre", "mis"], ["dire", "dit"], ["avoir", "eu"], ["être", "été"]]),
        G("J’ai ___ un bon film.", "Я посмотрела хороший фильм. (voir)", "vu"),
        G("Il a ___ le train.", "Он поехал на поезде. (prendre)", "pris"),
        G("Nous avons ___ du sport.", "Мы занимались спортом. (faire)", "fait"),
        G("Tu as ___ ce livre ?", "Ты прочитала эту книгу? (lire)", "lu"),
        G("Elle a ___ un message.", "Она написала сообщение. (écrire)", "écrit"),
        G("Je n’ai pas ___ venir.", "Я не смогла прийти. (pouvoir)", "pu"),
        G("J’ai ___ ton message.", "Я получила твоё сообщение. (recevoir)", "reçu"),
        C("comprendre →", ["compris", "comprendu", "compri"]),
        C("ouvrir →", ["ouvert", "ouvri", "ouvré"]),
        L("J’ai bu un café.", ["J’ai bu un café.", "J’ai vu un café.", "J’ai pu un café."]),
        O("Собери фразу «Что ты делала?»", ["as", "Qu’est-ce", "que", "tu", "fait"], "qu'est-ce que tu as fait"),
        D("J’ai mis un pull.", "j'ai mis un pull"),
        D("Vous avez compris ?", "vous avez compris"),
        T("Я выпила кофе.", "j'ai bu un café", "j'ai bu du café"),
        T("Мы поняли.", "nous avons compris", "on a compris"),
    ),
    "homework": hw("Напиши, что ты сделала за эти выходные или за прошлую неделю — 5 предложений, в каждом неправильное причастие (fait, vu, pris, lu, bu, écrit…).",
                   "Ce week-end, j’ai fait une promenade. J’ai vu un film français. J’ai lu vingt pages. J’ai bu un chocolat chaud. J’ai écrit un message à ma mère.", 20),
}

# ---------------------------------------------------------------- 28 октября
CONTENT["2026-10-28"] = {
    "topic": "Passé composé с être · предлоги места",
    "theory": [
        th("Глаголы движения идут с être",
           "Около 15 глаголов образуют passé composé с être — в основном это движение и смена состояния: aller, venir, arriver, partir, entrer, sortir, monter, descendre, rester, tomber, naître, mourir, retourner, passer. Плюс все возвратные глаголы.",
           exs=[["Je suis allée à Paris.", "Я съездила в Париж."], ["Il est arrivé hier.", "Он приехал вчера."], ["Je me suis levée tôt.", "Я встала рано."]]),
        th("Причастие согласуется с подлежащим",
           "С être причастие ведёт себя как прилагательное: + e для женского рода, + s для множественного.",
           table=[["je suis allé(e)", "я пошёл / пошла"], ["tu es allé(e)", "ты пошёл / пошла"], ["il est allé / elle est allée", "он / она пошла"], ["nous sommes allé(e)s", "мы пошли"], ["vous êtes allé(e)(s)", "вы пошли"], ["ils sont allés / elles sont allées", "они пошли"]]),
        th("Где? Предлоги места",
           "devant — перед, derrière — за, à côté de — рядом с, en face de — напротив, près de — недалеко от, loin de — далеко от, au milieu de — посередине. de + le = du: à côté du café.",
           exs=[["La pharmacie est à côté de la banque.", "Аптека рядом с банком."], ["J’habite près du centre.", "Я живу недалеко от центра."], ["Le chat est derrière la porte.", "Кот за дверью."]]),
    ],
    "vocab": [
        w("devant", "devant", "перед", "Je t’attends devant la gare.", "Жду тебя перед вокзалом."),
        w("derriere", "derrière", "за, позади", "Le jardin est derrière la maison.", "Сад за домом."),
        w("a-cote", "à côté de", "рядом с", "La banque est à côté du café.", "Банк рядом с кафе.", None, ["côté"]),
        w("en-face", "en face de", "напротив", "L’arrêt est en face de l’école.", "Остановка напротив школы.", None, ["face"]),
        w("pres", "près de", "недалеко от", "J’habite près d’ici.", "Я живу недалеко отсюда.", None, ["près"]),
        w("loin", "loin de", "далеко от", "C’est loin de la gare ?", "Это далеко от вокзала?", None, ["loin"]),
        w("milieu", "au milieu de", "посередине", "Au milieu de la place.", "Посреди площади.", None, ["milieu"]),
        w("pendant", "pendant", "в течение, во время", "Pendant les vacances.", "Во время каникул."),
        w("jusqu-a", "jusqu’à", "до (какого-то места/времени)", "Allez jusqu’à la gare.", "Идите до вокзала.", None, ["jusqu"]),
        w("vers", "vers", "около (времени); к (направление)", "J’arrive vers huit heures.", "Приеду около восьми."),
        w("naitre", "naître → né(e)", "родиться", "Je suis née en mai.", "Я родилась в мае.", None, ["né", "née"]),
        w("tomber", "tomber", "падать", "Il est tombé.", "Он упал.", forms=["tombé", "tombée", "tombe"]),
        w("monter", "monter · descendre", "подниматься · спускаться", "Je suis montée au cinquième étage.", "Я поднялась на пятый этаж.", None, ["monter", "monté", "descendre", "descendu"]),
    ],
    "topics": [
        topic("t-pc-etre", "Passé composé с être",
              ("elle (aller) →", ["elle est allée", "elle a allé", "elle est allé"]),
              ("ils (partir) →", ["ils sont partis", "ils ont parti", "ils sont parti"]),
              ("je (se lever), женщина →", ["je me suis levée", "j’ai me levé", "je suis levée me"])),
        topic("t-lieu", "Предлоги места",
              ("«рядом с кафе»", ["à côté du café", "à côté le café", "côté de café"]),
              ("«напротив школы»", ["en face de l’école", "en face l’école", "face à de l’école"])),
    ],
    "exercises": ex(
        C("aller → passé composé", ["je suis allé(e)", "j’ai allé"]),
        C("regarder → passé composé", ["j’ai regardé", "je suis regardé"]),
        C("partir → passé composé", ["je suis parti(e)", "j’ai parti"]),
        G("Elle est ___ à Paris.", "Она съездила в Париж. (aller)", "allée"),
        G("Ils sont ___ hier.", "Они приехали вчера. (arriver)", "arrivés"),
        G("Nous ___ restés à la maison.", "Мы остались дома.", "sommes"),
        G("Je me suis ___ à sept heures.", "Я (женщина) встала в семь. (se lever)", "levée"),
        G("La banque est à côté ___ café.", "Банк рядом с кафе.", "du"),
        G("J’habite ___ du centre.", "Я живу недалеко от центра.", "près"),
        L("Elle est partie.", ["Elle est partie.", "Elle a parti.", "Il est parti."]),
        M("Где?", [["devant", "перед"], ["derrière", "за"], ["en face de", "напротив"], ["loin de", "далеко от"], ["au milieu de", "посередине"]]),
        O("Собери фразу «Я родилась в мае»", ["suis", "Je", "née", "en", "mai"], "je suis née en mai"),
        O("Собери фразу «Аптека напротив вокзала»", ["est", "La", "pharmacie", "en", "face", "de", "la", "gare"], "la pharmacie est en face de la gare"),
        D("Nous sommes allés au cinéma.", "nous sommes allés au cinéma"),
        D("Il est tombé dans la rue.", "il est tombé dans la rue"),
        T("Она осталась дома.", "elle est restée à la maison"),
        T("Кот за дверью.", "le chat est derrière la porte"),
    ),
    "homework": hw("Расскажи о поездке или прогулке в прошлом: куда ты пошла/поехала, когда вышла и вернулась (глаголы с être!), что увидела (с avoir). Добавь 2 предложения о том, где что находится, с предлогами места.",
                   "Samedi, je suis allée au centre. Je suis partie à dix heures. J’ai vu une belle église. Le café est en face de l’église. Je suis rentrée vers six heures.", 30),
}

# ---------------------------------------------------------------- 29 октября
CONTENT["2026-10-29"] = {
    "topic": "Предлоги времени и места · повторение месяца",
    "theory": [
        th("Где и куда",
           "Город — à: à Paris. Страна женского рода — en, мужского — au, во мн. ч. — aux. Внутри — dans: dans la maison. У кого-то — chez: chez mes parents.",
           exs=[["Je vais à Lyon.", "Я еду в Лион."], ["Il habite au Portugal.", "Он живёт в Португалии."], ["Je suis chez moi.", "Я дома."]]),
        th("depuis, pendant, il y a",
           "depuis — «с / уже» для того, что длится до сих пор: j’apprends le français depuis un mois. pendant — «в течение» законченного отрезка: j’ai travaillé pendant deux heures. il y a — «назад»: je suis arrivée il y a une semaine.",
           exs=[["J’apprends le français depuis un mois.", "Я учу французский уже месяц."], ["J’ai dormi pendant huit heures.", "Я спала восемь часов."], ["Il est parti il y a dix minutes.", "Он ушёл десять минут назад."]]),
        th("en и à со временем",
           "en + месяц, год, сезон (кроме весны): en octobre, en 2026, en été, en hiver, но au printemps. à + час: à huit heures.",
           exs=[["En été, il fait chaud.", "Летом жарко."], ["Au printemps, il pleut.", "Весной идёт дождь."]]),
        th("Итоги месяца",
           "За октябрь ты прошла: présent всех групп, возвратные глаголы, артикли, притяжательные, прилагательные, числа, futur proche, impératif, passé récent и passé composé. Завтра — контрольный пробный TCF.",
           exs=[["J’apprends le français depuis un mois.", "Я учу французский уже месяц."], ["Demain, je vais passer le test.", "Завтра я пройду тест."]]),
    ],
    "vocab": [
        w("il-y-a-exist", "il y a", "есть, имеется", "Il y a un café ici.", "Здесь есть кафе."),
        w("c-est", "c’est · ce sont", "это", "C’est mon frère. Ce sont mes amis.", "Это мой брат. Это мои друзья."),
        w("d-accord", "d’accord", "согласна; хорошо", "D’accord, à demain !", "Хорошо, до завтра!", None, ["accord"]),
        w("bien-sur", "bien sûr", "конечно", "Bien sûr, je viens.", "Конечно, я приду."),
        w("pas-du-tout", "pas du tout", "совсем нет", "Je ne suis pas du tout fatiguée.", "Я совсем не устала."),
        w("peut-etre", "peut-être", "может быть", "Peut-être demain.", "Может быть, завтра."),
        w("a-mon-avis", "à mon avis", "по-моему", "À mon avis, c’est vrai.", "По-моему, это правда.", None, ["avis"]),
        w("ca-depend", "ça dépend", "смотря как, это зависит", "— Tu viens ? — Ça dépend.", "— Придёшь? — Смотря как.", None, ["dépend"]),
        w("pas-mal", "pas mal", "неплохо", "Ce film est pas mal.", "Этот фильм неплохой."),
        w("ca-marche", "ça marche", "договорились; работает", "Demain à dix heures ? — Ça marche !", "Завтра в десять? — Договорились!", None, ["marche"]),
        w("saisons", "l’été · l’hiver · l’automne · le printemps", "лето · зима · осень · весна", "En hiver, il neige.", "Зимой идёт снег.", None, ["été", "hiver", "automne", "printemps"]),
        w("aujourd-hui", "aujourd’hui", "сегодня", "Aujourd’hui, il fait beau.", "Сегодня хорошая погода.", None, ["aujourd"]),
    ],
    "topics": [
        topic("t-depuis", "depuis / pendant / il y a",
              ("«Я учу французский уже месяц»", ["J’apprends le français depuis un mois.", "J’apprends le français pendant un mois.", "J’apprends le français il y a un mois."]),
              ("«Он ушёл 10 минут назад»", ["Il est parti il y a dix minutes.", "Il est parti depuis dix minutes.", "Il est parti pendant dix minutes."]),
              ("«Я спала 8 часов»", ["J’ai dormi pendant huit heures.", "J’ai dormi depuis huit heures.", "J’ai dormi il y a huit heures."])),
    ],
    "exercises": ex(
        G("Je vais ___ Lyon.", "Я еду в Лион.", "à"),
        G("Il habite ___ Portugal.", "Он живёт в Португалии.", "au"),
        G("Nous sommes ___ nos amis.", "Мы у друзей.", "chez"),
        G("J’apprends le français ___ un mois.", "Я учу французский уже месяц.", "depuis"),
        G("J’ai travaillé ___ deux heures.", "Я работала два часа.", "pendant"),
        G("Il est parti ___ dix minutes.", "Он ушёл десять минут назад.", "il y a"),
        C("«весной»", ["au printemps", "en printemps", "à printemps"]),
        C("«в октябре»", ["en octobre", "à octobre", "au octobre"]),
        J("повторение месяца", [["je (être)", "suis"], ["nous (aller)", "allons"], ["ils (faire)", "font"], ["vous (finir)", "finissez"], ["elle (se lever)", "se lève"], ["tu (vouloir)", "veux"]], q="Повторение: présent"),
        C("«Я поеду в Париж» (futur proche)", ["Je vais aller à Paris.", "Je viens d’aller à Paris.", "Je suis allée à Paris."]),
        C("«Я съездила в Париж» (passé composé)", ["Je suis allée à Paris.", "J’ai allé à Paris.", "Je vais aller à Paris."]),
        L("D’accord, à demain !", ["D’accord, à demain !", "Bien sûr, à bientôt !", "Pas du tout !"]),
        M("Полезные выражения", [["d’accord", "хорошо, согласна"], ["peut-être", "может быть"], ["à mon avis", "по-моему"], ["pas du tout", "совсем нет"], ["ça marche", "договорились"]]),
        O("Собери фразу «Я учу французский уже месяц»", ["apprends", "J’", "le", "français", "depuis", "un", "mois"], "j'apprends le français depuis un mois"),
        D("Au printemps, il pleut souvent.", "au printemps il pleut souvent"),
        T("Сегодня хорошая погода.", "aujourd'hui il fait beau", "il fait beau aujourd'hui"),
        T("Это мои друзья.", "ce sont mes amis", "c'est mes amis"),
    ),
    "homework": hw("Итоговое письмо месяца (10–12 предложений): расскажи, как прошёл твой первый месяц французского. Используй present (что ты делаешь каждый день), passé composé (что ты уже сделала), futur proche (что будешь делать дальше) и depuis.",
                   "J’apprends le français depuis un mois. Tous les jours, j’écoute un podcast et je fais des exercices. J’ai appris beaucoup de mots. J’ai lu quinze chapitres du Petit Prince. Demain, je vais passer un test. En novembre, je vais apprendre l’imparfait.", 50),
}
