# -*- coding: utf-8 -*-
"""Неделя 1: 5–9 октября."""
from h import w, C, L, G, J, M, O, D, T, ex, th, topic, hw

CONTENT = {}

# ---------------------------------------------------------------- 5 октября
CONTENT["2026-10-05"] = {
    "topic": "Présent: глаголы на -er",
    "theory": [
        th("Первая группа — глаголы на -er",
           "Это самая большая группа: parler, aimer, habiter, travailler. Отбрасываем -er и добавляем окончания. Окончания -e, -es, -e, -ent не читаются, поэтому je parle, tu parles, il parle и ils parlent звучат одинаково.",
           table=[["je parle", "я говорю"], ["tu parles", "ты говоришь"], ["il / elle / on parle", "он / она говорит"], ["nous parlons", "мы говорим"], ["vous parlez", "вы говорите"], ["ils / elles parlent", "они говорят"]]),
        th("Перед гласной — сокращение и связывание",
           "Если глагол начинается с гласной или немой h, je превращается в j’, а в nous, vous, ils появляется связывание: nous‿aimons [нузэмон], ils‿habitent [ильзабит].",
           exs=[["J’aime le café.", "Я люблю кофе."], ["Nous habitons à Paris.", "Мы живём в Париже."], ["Ils aiment la musique.", "Они любят музыку."]]),
        th("Два орфографических исключения",
           "Чтобы сохранить звук, в форме nous пишут manger → nous mangeons (с e) и commencer → nous commençons (с ç).",
           exs=[["Nous mangeons à midi.", "Мы обедаем в полдень."], ["Nous commençons à huit heures.", "Мы начинаем в восемь."]]),
        th("Отрицание — как в прошлый раз",
           "ne … pas берут глагол в рамку: je ne parle pas. Перед гласной ne → n’: je n’aime pas.",
           exs=[["Je ne travaille pas le dimanche.", "Я не работаю по воскресеньям."], ["Elle n’habite pas ici.", "Она живёт не здесь."]]),
    ],
    "vocab": [
        w("notre", "notre / nos", "наш / наши", "Notre maison est petite.", "Наш дом маленький.", forms=["notre", "nos"]),
        w("votre", "votre / vos", "ваш / ваши", "C’est votre livre ?", "Это ваша книга?", forms=["votre", "vos"]),
        w("jour", "jour", "день", "Un jour, je vais à Paris.", "Однажды я поеду в Париж.", "m", ["jours"]),
        w("temps", "temps", "время; погода", "Je n’ai pas le temps.", "У меня нет времени.", "m"),
        w("petit", "petit / petite", "маленький", "Un petit café, s’il vous plaît.", "Маленький кофе, пожалуйста.", forms=["petit", "petite", "petits", "petites"]),
        w("grand", "grand / grande", "большой; высокий", "Paris est une grande ville.", "Париж — большой город.", forms=["grand", "grande", "grands", "grandes"]),
        w("meme", "même", "тот же самый; даже", "On a le même livre.", "У нас одна и та же книга."),
        w("autre", "autre", "другой", "Un autre café ?", "Ещё один кофе?", forms=["autres"]),
        w("encore", "encore", "ещё", "Encore une fois !", "Ещё раз!"),
        w("aussi", "aussi", "тоже, также", "Moi aussi.", "Я тоже."),
        w("tres", "très", "очень", "C’est très bon.", "Это очень вкусно."),
        w("rien", "rien", "ничего", "Je ne dis rien.", "Я ничего не говорю."),
        w("la-adv", "là", "там; здесь", "Je suis là.", "Я здесь."),
        w("alors", "alors", "тогда; итак", "Alors, on y va ?", "Итак, идём?"),
        w("quand", "quand", "когда", "Quand est-ce que tu arrives ?", "Когда ты приезжаешь?"),
        w("deja", "déjà", "уже", "Il est déjà là.", "Он уже здесь."),
        w("toujours", "toujours", "всегда; всё ещё", "Elle travaille toujours.", "Она всегда работает."),
        w("jamais", "ne … jamais", "никогда", "Je ne mange jamais de viande.", "Я никогда не ем мясо.", forms=["jamais"]),
        w("peu", "peu / un peu", "мало / немного", "Je parle un peu français.", "Я немного говорю по-французски."),
        w("beaucoup", "beaucoup", "много; очень (с глаголом)", "J’aime beaucoup Paris.", "Я очень люблю Париж."),
        w("trop", "trop", "слишком", "C’est trop cher.", "Это слишком дорого."),
        w("chose", "chose", "вещь", "C’est une bonne chose.", "Это хорошая вещь.", "f", ["choses"]),
        w("vie", "vie", "жизнь", "C’est la vie !", "Такова жизнь!", "f"),
        w("monde", "monde", "мир; люди", "Tout le monde est là.", "Все здесь.", "m"),
        w("main", "main", "рука (кисть)", "Donne-moi la main.", "Дай мне руку.", "f", ["mains"]),
        w("fois", "fois", "раз", "Une fois par semaine.", "Раз в неделю.", "f"),
        w("annee", "année / an", "год", "J’ai vingt ans.", "Мне двадцать лет.", "f", ["année", "années", "an", "ans"]),
        w("femme", "femme", "женщина; жена", "C’est une femme intelligente.", "Это умная женщина.", "f", ["femmes"]),
        w("enfant", "enfant", "ребёнок", "Ils ont deux enfants.", "У них двое детей.", "m", ["enfants"]),
        w("moment", "moment", "момент", "Un moment, s’il vous plaît.", "Минутку, пожалуйста.", "m"),
        w("ici", "ici", "здесь", "J’habite ici.", "Я живу здесь."),
        w("maintenant", "maintenant", "сейчас", "Je travaille maintenant.", "Я сейчас работаю."),
        w("apres", "après", "после", "Après le travail.", "После работы."),
        w("avant", "avant", "до, перед", "Avant le dîner.", "Перед ужином."),
        w("depuis", "depuis", "с (какого-то момента); уже (сколько-то)", "J’habite ici depuis un an.", "Я живу здесь уже год."),
        w("sous", "sous", "под", "Le chat est sous la table.", "Кот под столом."),
        w("entre", "entre", "между", "Entre nous.", "Между нами."),
        w("chez", "chez", "у (кого-то), к (кому-то домой)", "Je suis chez moi.", "Я дома."),
        w("parce-que", "parce que", "потому что", "Je reste parce que j’aime ça.", "Я остаюсь, потому что мне это нравится.", forms=["parce"]),
        w("donc", "donc", "поэтому, значит", "Je pense, donc je suis.", "Я мыслю, значит, существую."),
        w("puis", "puis", "потом", "D’abord le café, puis le travail.", "Сначала кофе, потом работа."),
        w("comment", "comment", "как", "Comment tu t’appelles ?", "Как тебя зовут?"),
        w("pourquoi", "pourquoi", "почему", "Pourquoi tu ris ?", "Почему ты смеёшься?"),
        w("quel", "quel / quelle", "какой / какая", "Quelle heure est-il ?", "Который час?", forms=["quel", "quelle", "quels", "quelles"]),
        w("bon", "bon / bonne", "хороший; вкусный", "Bonne journée !", "Хорошего дня!", forms=["bon", "bonne", "bons", "bonnes"]),
        w("nouveau", "nouveau / nouvelle", "новый / новая", "Une nouvelle vie.", "Новая жизнь.", forms=["nouveau", "nouvelle", "nouveaux", "nouvelles"]),
        w("dernier", "dernier / dernière", "последний", "La dernière fois.", "В последний раз.", forms=["dernier", "dernière"]),
        w("premier", "premier / première", "первый", "Le premier jour.", "Первый день.", forms=["premier", "première"]),
        w("ami", "ami / amie", "друг / подруга", "C’est mon amie Léa.", "Это моя подруга Леа.", forms=["ami", "amie", "amis", "amies"]),
        w("heure", "heure", "час", "Il est deux heures.", "Сейчас два часа.", "f", ["heures"]),
    ],
    "topics": [
        topic("t-er", "Présent: глаголы на -er",
              ("nous parl___", ["-ons", "-ez", "-ent"]),
              ("ils aim___", ["-ent", "-ons", "-es"]),
              ("tu travaill___", ["-es", "-e", "-ez"]),
              ("nous (manger) → ", ["mangeons", "mangons", "mangez"])),
    ],
    "exercises": ex(
        J("parler", [["je", "parle"], ["tu", "parles"], ["il", "parle"], ["nous", "parlons"], ["vous", "parlez"], ["ils", "parlent"]]),
        J("aimer", [["j’", "aime"], ["tu", "aimes"], ["elle", "aime"], ["nous", "aimons"], ["vous", "aimez"], ["elles", "aiment"]]),
        G("Nous ___ à Paris.", "Мы живём в Париже. (habiter)", "habitons"),
        G("Elle ___ le lundi.", "Она работает по понедельникам. (travailler)", "travaille"),
        G("Vous ___ anglais ?", "Вы говорите по-английски? (parler)", "parlez"),
        G("Ils ___ le café.", "Они любят кофе. (aimer)", "aiment"),
        G("Nous ___ à midi.", "Мы обедаем в полдень. (manger)", "mangeons"),
        C("Какие формы звучат одинаково?", ["je parle, tu parles, ils parlent", "nous parlons, vous parlez", "je parle, nous parlons"]),
        C("Как правильно: «Я не говорю по-английски»?", ["Je ne parle pas anglais.", "Je parle ne pas anglais.", "Je ne pas parle anglais."]),
        L("Nous habitons ici.", ["Nous habitons ici.", "Vous habitez ici.", "Ils habitent ici."]),
        M("Слова 51–100", [["toujours", "всегда"], ["jamais", "никогда"], ["ici", "здесь"], ["maintenant", "сейчас"], ["beaucoup", "много"]]),
        M("Вопросительные слова", [["pourquoi", "почему"], ["parce que", "потому что"], ["quand", "когда"], ["comment", "как"], ["quel", "какой"]]),
        O("Собери фразу «Я очень люблю французский»", ["aime", "J’", "le", "beaucoup", "français"], "j'aime beaucoup le français"),
        O("Собери фразу «Он здесь не работает»", ["ne", "Il", "pas", "travaille", "ici"], "il ne travaille pas ici"),
        D("Nous parlons un peu français.", "nous parlons un peu français"),
        D("Elle habite ici depuis un an.", "elle habite ici depuis un an"),
        T("Я говорю по-французски.", "je parle français"),
        T("Мы здесь работаем.", "nous travaillons ici"),
        T("Вы любите кофе?", "vous aimez le café", "aimez-vous le café", "est-ce que vous aimez le café"),
    ),
    "homework": hw("Напиши 5–6 предложений о себе с глаголами на -er: где ты живёшь (habiter), работаешь ли (travailler), что любишь (aimer) и на каких языках говоришь (parler). Одно предложение — с ne … pas.",
                   "J’habite à Moscou. Je travaille beaucoup. J’aime le café et la musique. Je parle russe et un peu français. Je n’aime pas le sport.", 20),
}

# ---------------------------------------------------------------- 6 октября
CONTENT["2026-10-06"] = {
    "topic": "Présent: глаголы на -ir (2-я группа)",
    "theory": [
        th("Вторая группа: finir, choisir, réussir",
           "Это глаголы на -ir, у которых во множественном числе появляется -iss-. Окончания: -is, -is, -it, -issons, -issez, -issent.",
           table=[["je finis", "я заканчиваю"], ["tu finis", "ты заканчиваешь"], ["il / elle finit", "он / она заканчивает"], ["nous finissons", "мы заканчиваем"], ["vous finissez", "вы заканчиваете"], ["ils / elles finissent", "они заканчивают"]]),
        th("Кто ещё в этой группе",
           "choisir — выбирать, réussir — добиться успеха, сдать, grandir — расти, réfléchir — думать, размышлять, remplir — заполнять.",
           exs=[["Je choisis ce livre.", "Я выбираю эту книгу."], ["Les enfants grandissent vite.", "Дети быстро растут."], ["Nous réfléchissons.", "Мы думаем."]]),
        th("Осторожно: не все глаголы на -ir такие",
           "partir, sortir, dormir — это третья группа, без -iss-: je pars, nous partons; je dors, nous dormons. Их формы учим по одной.",
           exs=[["Je pars à huit heures.", "Я ухожу в восемь."], ["Nous dormons bien.", "Мы хорошо спим."]]),
    ],
    "vocab": [
        w(i, fr, ru, ex_, exRu, forms=forms) for (i, fr, ru, ex_, exRu, forms) in [
            ("parler", "parler", "говорить", "Tu parles français ?", "Ты говоришь по-французски?", ["parle", "parles", "parlons", "parlez", "parlent"]),
            ("aimer", "aimer", "любить, нравиться", "J’aime le chocolat.", "Я люблю шоколад.", ["aime", "aimes", "aimons", "aimez", "aiment"]),
            ("habiter", "habiter", "жить (где-то)", "J’habite à Kazan.", "Я живу в Казани.", ["habite", "habites", "habitons", "habitez", "habitent"]),
            ("travailler", "travailler", "работать", "Il travaille ici.", "Он работает здесь.", ["travaille", "travailles", "travaillons", "travaillez", "travaillent"]),
            ("manger", "manger", "есть, кушать", "On mange ensemble ?", "Поедим вместе?", ["mange", "manges", "mangeons", "mangez", "mangent"]),
            ("regarder", "regarder", "смотреть", "Je regarde un film.", "Я смотрю фильм.", ["regarde", "regardes", "regardons", "regardez", "regardent"]),
            ("ecouter", "écouter", "слушать", "J’écoute un podcast.", "Я слушаю подкаст.", ["écoute", "écoutes", "écoutons", "écoutez", "écoutent"]),
            ("chercher", "chercher", "искать", "Je cherche la gare.", "Я ищу вокзал.", ["cherche", "cherches", "cherchons", "cherchez", "cherchent"]),
            ("trouver", "trouver", "находить", "Je ne trouve pas mes clés.", "Я не нахожу ключи.", ["trouve", "trouves", "trouvons", "trouvez", "trouvent"]),
            ("donner", "donner", "давать", "Donne-moi ça.", "Дай мне это.", ["donne", "donnes", "donnons", "donnez", "donnent"]),
            ("penser", "penser", "думать", "Je pense à toi.", "Я думаю о тебе.", ["pense", "penses", "pensons", "pensez", "pensent"]),
            ("arriver", "arriver", "приезжать, приходить", "J’arrive !", "Иду! (уже прихожу)", ["arrive", "arrives", "arrivons", "arrivez", "arrivent"]),
            ("entrer", "entrer", "входить", "Entrez, s’il vous plaît.", "Входите, пожалуйста.", ["entre", "entres", "entrons", "entrez", "entrent"]),
            ("rester", "rester", "оставаться", "Je reste à la maison.", "Я остаюсь дома.", ["reste", "restes", "restons", "restez", "restent"]),
            ("passer", "passer", "проходить; проводить (время)", "Je passe le week-end à Paris.", "Я провожу выходные в Париже.", ["passe", "passes", "passons", "passez", "passent"]),
            ("demander", "demander", "спрашивать, просить", "Je demande le chemin.", "Я спрашиваю дорогу.", ["demande", "demandes", "demandons", "demandez", "demandent"]),
            ("jouer", "jouer", "играть", "Les enfants jouent.", "Дети играют.", ["joue", "joues", "jouons", "jouez", "jouent"]),
            ("commencer", "commencer", "начинать", "Le film commence.", "Фильм начинается.", ["commence", "commences", "commençons", "commencez", "commencent"]),
            ("acheter", "acheter", "покупать", "J’achète du pain.", "Я покупаю хлеб.", ["achète", "achètes", "achetons", "achetez", "achètent"]),
            ("payer", "payer", "платить", "Je paie par carte.", "Я плачу картой.", ["paie", "paies", "payons", "payez", "paient"]),
            ("appeler", "appeler", "звонить; звать", "Je t’appelle ce soir.", "Я позвоню тебе вечером.", ["appelle", "appelles", "appelons", "appelez", "appellent"]),
            ("preferer", "préférer", "предпочитать", "Je préfère le thé.", "Я предпочитаю чай.", ["préfère", "préfères", "préférons", "préférez", "préfèrent"]),
            ("finir", "finir", "заканчивать", "Je finis à six heures.", "Я заканчиваю в шесть.", ["finis", "finit", "finissons", "finissez", "finissent"]),
            ("choisir", "choisir", "выбирать", "Tu choisis quoi ?", "Что ты выбираешь?", ["choisis", "choisit", "choisissons", "choisissez", "choisissent"]),
            ("reussir", "réussir", "добиться успеха; сдать", "Elle réussit toujours.", "У неё всегда получается.", ["réussis", "réussit", "réussissons", "réussissez", "réussissent"]),
            ("grandir", "grandir", "расти", "Les enfants grandissent.", "Дети растут.", ["grandis", "grandit", "grandissons", "grandissez", "grandissent"]),
            ("partir", "partir", "уезжать, уходить", "Le train part à midi.", "Поезд уходит в полдень.", ["pars", "part", "partons", "partez", "partent"]),
            ("sortir", "sortir", "выходить", "Je sors ce soir.", "Я иду гулять сегодня вечером.", ["sors", "sort", "sortons", "sortez", "sortent"]),
            ("dormir", "dormir", "спать", "Je dors mal.", "Я плохо сплю.", ["dors", "dort", "dormons", "dormez", "dorment"]),
            ("venir", "venir", "приходить, приезжать", "Tu viens avec moi ?", "Ты идёшь со мной?", ["viens", "vient", "venons", "venez", "viennent"]),
            ("prendre", "prendre", "брать; ехать (на транспорте)", "Je prends le bus.", "Я еду на автобусе.", ["prends", "prend", "prenons", "prenez", "prennent"]),
            ("mettre", "mettre", "класть; надевать", "Je mets un pull.", "Я надеваю свитер.", ["mets", "met", "mettons", "mettez", "mettent"]),
            ("savoir", "savoir", "знать; уметь", "Je ne sais pas.", "Я не знаю.", ["sais", "sait", "savons", "savez", "savent"]),
            ("connaitre", "connaître", "знать (кого-то, место)", "Tu connais Paris ?", "Ты знаешь Париж?", ["connais", "connaît", "connaissons", "connaissez", "connaissent"]),
            ("vouloir", "vouloir", "хотеть", "Je veux un café.", "Я хочу кофе.", ["veux", "veut", "voulons", "voulez", "veulent", "voudrais"]),
            ("devoir", "devoir", "быть должным", "Je dois partir.", "Мне нужно уходить.", ["dois", "doit", "devons", "devez", "doivent"]),
            ("lire", "lire", "читать", "Je lis un livre.", "Я читаю книгу.", ["lis", "lit", "lisons", "lisez", "lisent"]),
            ("ecrire", "écrire", "писать", "J’écris un message.", "Я пишу сообщение.", ["écris", "écrit", "écrivons", "écrivez", "écrivent"]),
            ("boire", "boire", "пить", "Je bois de l’eau.", "Я пью воду.", ["bois", "boit", "buvons", "buvez", "boivent"]),
            ("vivre", "vivre", "жить", "Vivre en France.", "Жить во Франции.", ["vis", "vit", "vivons", "vivez", "vivent"]),
            ("comprendre", "comprendre", "понимать", "Je ne comprends pas.", "Я не понимаю.", ["comprends", "comprend", "comprenons", "comprenez", "comprennent"]),
            ("apprendre", "apprendre", "учить (что-то)", "J’apprends le français.", "Я учу французский.", ["apprends", "apprend", "apprenons", "apprenez", "apprennent"]),
            ("attendre", "attendre", "ждать", "J’attends le bus.", "Я жду автобус.", ["attends", "attend", "attendons", "attendez", "attendent"]),
            ("repondre", "répondre", "отвечать", "Réponds-moi !", "Ответь мне!", ["réponds", "répond", "répondons", "répondez", "répondent"]),
            ("entendre", "entendre", "слышать", "Tu m’entends ?", "Ты меня слышишь?", ["entends", "entend", "entendons", "entendez", "entendent"]),
            ("perdre", "perdre", "терять; проигрывать", "Je perds toujours mes clés.", "Я всегда теряю ключи.", ["perds", "perd", "perdons", "perdez", "perdent"]),
            ("croire", "croire", "верить; думать", "Je crois que oui.", "Думаю, что да.", ["crois", "croit", "croyons", "croyez", "croient"]),
            ("ouvrir", "ouvrir", "открывать", "J’ouvre la fenêtre.", "Я открываю окно.", ["ouvre", "ouvres", "ouvrons", "ouvrez", "ouvrent"]),
            ("courir", "courir", "бегать", "Je cours le matin.", "Я бегаю по утрам.", ["cours", "court", "courons", "courez", "courent"]),
            ("recevoir", "recevoir", "получать", "Je reçois un message.", "Я получаю сообщение.", ["reçois", "reçoit", "recevons", "recevez", "reçoivent"]),
        ]
    ],
    "topics": [
        topic("t-ir", "Présent: глаголы на -ir (finir)",
              ("nous (finir) →", ["finissons", "finons", "finirons"]),
              ("ils (choisir) →", ["choisissent", "choisent", "choisirent"]),
              ("je (partir) →", ["pars", "partis", "partissons"])),
    ],
    "exercises": ex(
        J("finir", [["je", "finis"], ["tu", "finis"], ["il", "finit"], ["nous", "finissons"], ["vous", "finissez"], ["ils", "finissent"]]),
        J("choisir", [["je", "choisis"], ["tu", "choisis"], ["elle", "choisit"], ["nous", "choisissons"], ["vous", "choisissez"], ["elles", "choisissent"]]),
        G("Nous ___ le travail à six heures.", "Мы заканчиваем работу в шесть. (finir)", "finissons"),
        G("Elle ___ une robe.", "Она выбирает платье. (choisir)", "choisit"),
        G("Les étudiants ___ l’examen.", "Студенты сдают экзамен. (réussir)", "réussissent"),
        G("Tu ___ vite !", "Ты быстро растёшь! (grandir)", "grandis"),
        C("partir — к какой группе относится?", ["к третьей: je pars, nous partons", "ко второй: nous partissons"]),
        C("nous (dormir) →", ["dormons", "dormissons", "dormez"]),
        L("Ils finissent à midi.", ["Il finit à midi.", "Ils finissent à midi."], 1),
        M("Глаголы", [["manger", "есть"], ["boire", "пить"], ["lire", "читать"], ["écrire", "писать"], ["dormir", "спать"]]),
        M("Глаголы", [["acheter", "покупать"], ["attendre", "ждать"], ["chercher", "искать"], ["trouver", "находить"], ["ouvrir", "открывать"]]),
        O("Собери фразу «Фильм заканчивается в десять»", ["Le", "film", "à", "finit", "dix", "heures"], "le film finit à dix heures"),
        O("Собери фразу «Я не понимаю»", ["comprends", "Je", "pas", "ne"], "je ne comprends pas"),
        D("Nous finissons le travail.", "nous finissons le travail"),
        D("Tu choisis quel livre ?", "tu choisis quel livre"),
        T("Я выбираю эту книгу.", "je choisis ce livre"),
        T("Дети растут.", "les enfants grandissent"),
        T("Я учу французский.", "j'apprends le français"),
    ),
    "homework": hw("Напиши 5–6 предложений о своём обычном дне, используя глаголы из сегодняшнего списка: во сколько начинаешь и заканчиваешь (commencer, finir), что читаешь, слушаешь, смотришь, пьёшь.",
                   "Je commence le travail à neuf heures. Je finis à six heures. Le soir, je lis un livre et j’écoute un podcast. Je bois du thé.", 20),
}

# ---------------------------------------------------------------- 7 октября
CONTENT["2026-10-07"] = {
    "topic": "aller, faire, venir, prendre · страны",
    "theory": [
        th("Четыре частых неправильных глагола",
           "Их нужно выучить наизусть — они встречаются в каждом разговоре.",
           table=[["aller: je vais, tu vas, il va", "идти, ехать"], ["nous allons, vous allez, ils vont", ""],
                  ["faire: je fais, tu fais, il fait", "делать"], ["nous faisons, vous faites, ils font", ""],
                  ["venir: je viens, tu viens, il vient", "приходить"], ["nous venons, vous venez, ils viennent", ""],
                  ["prendre: je prends, tu prends, il prend", "брать"], ["nous prenons, vous prenez, ils prennent", ""]]),
        th("Страны: в / из",
           "Женский род (обычно на -e): en France, de France. Мужской: au Canada, du Canada. Множественное число: aux États-Unis, des États-Unis. Перед гласной — d’: d’Italie. Города — всегда à и de: à Paris, de Moscou.",
           exs=[["Je vais en Espagne.", "Я еду в Испанию."], ["Il habite au Japon.", "Он живёт в Японии."], ["Nous venons des États-Unis.", "Мы из США."], ["Elle vient d’Italie.", "Она из Италии."]]),
        th("Национальность",
           "Национальность — прилагательное: мужской род + e для женского (français → française), -ien → -ienne (italien → italienne). Пишется с маленькой буквы, без артикля: Je suis russe.",
           exs=[["Je suis russe.", "Я русская."], ["Il est canadien, elle est canadienne.", "Он канадец, она канадка."]]),
    ],
    "vocab": [
        w("pays-fr", "la France · français(e)", "Франция · француз(женка)", "Je vais en France.", "Я еду во Францию.", "f", ["france", "français", "française"]),
        w("pays-ru", "la Russie · russe", "Россия · русский", "Je viens de Russie.", "Я из России.", "f", ["russie", "russe"]),
        w("pays-de", "l’Allemagne · allemand(e)", "Германия · немец(ка)", "Il habite en Allemagne.", "Он живёт в Германии.", "f", ["allemagne", "allemand", "allemande"]),
        w("pays-es", "l’Espagne · espagnol(e)", "Испания · испанец(ка)", "Elle parle espagnol.", "Она говорит по-испански.", "f", ["espagne", "espagnol", "espagnole"]),
        w("pays-it", "l’Italie · italien(ne)", "Италия · итальянец(ка)", "Il vient d’Italie.", "Он из Италии.", "f", ["italie", "italien", "italienne"]),
        w("pays-gb", "l’Angleterre · anglais(e)", "Англия · англичанин(ка)", "Je parle anglais.", "Я говорю по-английски.", "f", ["angleterre", "anglais", "anglaise"]),
        w("pays-us", "les États-Unis · américain(e)", "США · американец(ка)", "Ils vont aux États-Unis.", "Они едут в США.", None, ["américain", "américaine"]),
        w("pays-ca", "le Canada · canadien(ne)", "Канада · канадец(ка)", "J’habite au Canada.", "Я живу в Канаде.", "m", ["canada", "canadien", "canadienne"]),
        w("pays-cn", "la Chine · chinois(e)", "Китай · китаец(янка)", "Elle apprend le chinois.", "Она учит китайский.", "f", ["chine", "chinois", "chinoise"]),
        w("pays-jp", "le Japon · japonais(e)", "Япония · японец(ка)", "Tu vas au Japon ?", "Ты едешь в Японию?", "m", ["japon", "japonais", "japonaise"]),
        w("pays-br", "le Brésil · brésilien(ne)", "Бразилия · бразилец(ьянка)", "Il vient du Brésil.", "Он из Бразилии.", "m", ["brésil", "brésilien", "brésilienne"]),
        w("pays-be", "la Belgique · belge", "Бельгия · бельгиец(ка)", "Bruxelles est en Belgique.", "Брюссель в Бельгии.", "f", ["belgique", "belge"]),
        w("pays-ch", "la Suisse · suisse", "Швейцария · швейцарец(ка)", "Il travaille en Suisse.", "Он работает в Швейцарии.", "f", ["suisse"]),
        w("pays-pt", "le Portugal · portugais(e)", "Португалия · португалец(ка)", "On va au Portugal.", "Мы едем в Португалию.", "m", ["portugal", "portugais", "portugaise"]),
        w("pays-ma", "le Maroc · marocain(e)", "Марокко · марокканец(ка)", "Elle vient du Maroc.", "Она из Марокко.", "m", ["maroc", "marocain", "marocaine"]),
        w("pays-pl", "la Pologne · polonais(e)", "Польша · поляк(полька)", "Hugo habite en Pologne.", "Юго живёт в Польше.", "f", ["pologne", "polonais", "polonaise"]),
        w("pays-nl", "les Pays-Bas · néerlandais(e)", "Нидерланды · нидерландец(ка)", "Hélène habite aux Pays-Bas.", "Элен живёт в Нидерландах.", None, ["néerlandais", "néerlandaise"]),
        w("pays", "un pays", "страна", "Un beau pays.", "Красивая страна.", "m"),
        w("ville", "une ville", "город", "Une grande ville.", "Большой город.", "f", ["ville", "villes"]),
    ],
    "topics": [
        topic("t-aller-faire", "aller, faire, venir, prendre",
              ("ils (aller) →", ["vont", "allent", "vais"]),
              ("vous (faire) →", ["faites", "faisez", "font"]),
              ("ils (venir) →", ["viennent", "venent", "vient"]),
              ("nous (prendre) →", ["prenons", "prendons", "prennons"])),
        topic("t-pays", "Предлоги со странами",
              ("Я еду ___ France", ["en", "au", "à"]),
              ("Он живёт ___ Canada", ["au", "en", "aux"]),
              ("Мы едем ___ États-Unis", ["aux", "au", "en"])),
    ],
    "exercises": ex(
        J("aller", [["je", "vais"], ["tu", "vas"], ["il", "va"], ["nous", "allons"], ["vous", "allez"], ["ils", "vont"]]),
        J("faire", [["je", "fais"], ["tu", "fais"], ["elle", "fait"], ["nous", "faisons"], ["vous", "faites"], ["elles", "font"]]),
        J("venir", [["je", "viens"], ["tu", "viens"], ["il", "vient"], ["nous", "venons"], ["vous", "venez"], ["ils", "viennent"]]),
        J("prendre", [["je", "prends"], ["tu", "prends"], ["on", "prend"], ["nous", "prenons"], ["vous", "prenez"], ["ils", "prennent"]]),
        G("Je vais ___ France.", "Я еду во Францию.", "en"),
        G("Il habite ___ Canada.", "Он живёт в Канаде.", "au"),
        G("Nous allons ___ États-Unis.", "Мы едем в США.", "aux"),
        G("Elle vient ___ Italie.", "Она из Италии.", "d'", "d’"),
        G("Tu viens ___ Japon ?", "Ты из Японии?", "du"),
        C("Женский род от italien —", ["italienne", "italiene", "italiennee"]),
        C("Как правильно?", ["Je suis russe.", "Je suis une Russe.", "Je suis Russe femme."]),
        L("Ils vont à Paris.", ["Il va à Paris.", "Ils font à Paris.", "Ils vont à Paris."], 2),
        M("Страны", [["l’Allemagne", "Германия"], ["l’Espagne", "Испания"], ["la Chine", "Китай"], ["le Japon", "Япония"], ["la Pologne", "Польша"]]),
        O("Собери фразу «Я езжу на метро»", ["prends", "Je", "le", "métro"], "je prends le métro"),
        D("Ils font du sport.", "ils font du sport"),
        D("Vous venez d’où ?", "vous venez d'où"),
        T("Я еду в Испанию.", "je vais en espagne"),
        T("Она русская.", "elle est russe"),
        T("Мы из Бразилии.", "nous venons du brésil", "nous sommes du brésil", "on vient du brésil"),
    ),
    "homework": hw("Напиши 5–6 предложений: откуда ты и какой ты национальности, в каких странах была или живут твои друзья, куда хочешь поехать (Je vais…) и что ты обычно делаешь по выходным (faire).",
                   "Je suis russe. Je viens de Moscou. Mon amie habite en Allemagne. En été, je vais en Italie. Le week-end, je fais du sport.", 20),
}

# ---------------------------------------------------------------- 8 октября
CONTENT["2026-10-08"] = {
    "topic": "pouvoir, vouloir, devoir, savoir · профессии",
    "theory": [
        th("Модальные глаголы + инфинитив",
           "После них второй глагол стоит в инфинитиве: je peux venir, je veux dormir, je dois partir, je sais nager.",
           table=[["pouvoir: je peux, tu peux, il peut", "мочь"], ["nous pouvons, vous pouvez, ils peuvent", ""],
                  ["vouloir: je veux, tu veux, il veut", "хотеть"], ["nous voulons, vous voulez, ils veulent", ""],
                  ["devoir: je dois, tu dois, il doit", "быть должным"], ["nous devons, vous devez, ils doivent", ""],
                  ["savoir: je sais, tu sais, il sait", "знать, уметь"], ["nous savons, vous savez, ils savent", ""]]),
        th("Вежливое «я бы хотела»",
           "В магазине и кафе вместо je veux говорят je voudrais — это звучит вежливо.",
           exs=[["Je voudrais un café, s’il vous plaît.", "Я бы хотела кофе, пожалуйста."], ["Vous pouvez répéter ?", "Можете повторить?"]]),
        th("Профессия — без артикля",
           "Je suis médecin, elle est journaliste. Артикль появляется только с прилагательным: c’est un bon médecin. Многие профессии имеют женскую форму: serveur → serveuse, acteur → actrice, infirmier → infirmière.",
           exs=[["Je suis étudiante.", "Я студентка."], ["C’est une bonne actrice.", "Это хорошая актриса."]]),
    ],
    "vocab": [
        w("metier", "un métier", "профессия", "Tu fais quel métier ?", "Кем ты работаешь?", "m"),
        w("medecin", "médecin", "врач", "Mon père est médecin.", "Мой папа врач.", "m"),
        w("professeur", "professeur / prof", "преподаватель", "Elle est prof de français.", "Она преподаватель французского.", "m", ["professeur", "prof", "professeure"]),
        w("etudiant", "étudiant / étudiante", "студент / студентка", "Je suis étudiante.", "Я студентка.", forms=["étudiant", "étudiante"]),
        w("ingenieur", "ingénieur(e)", "инженер", "Il est ingénieur.", "Он инженер.", forms=["ingénieur", "ingénieure"]),
        w("avocat", "avocat / avocate", "адвокат, юрист", "Elle est avocate.", "Она адвокат.", forms=["avocat", "avocate"]),
        w("infirmier", "infirmier / infirmière", "медбрат / медсестра", "Ma sœur est infirmière.", "Моя сестра медсестра.", forms=["infirmier", "infirmière"]),
        w("serveur", "serveur / serveuse", "официант / официантка", "Le serveur arrive.", "Официант идёт.", forms=["serveur", "serveuse"]),
        w("vendeur", "vendeur / vendeuse", "продавец", "La vendeuse est sympa.", "Продавщица милая.", forms=["vendeur", "vendeuse"]),
        w("acteur", "acteur / actrice", "актёр / актриса", "C’est une actrice célèbre.", "Это знаменитая актриса.", forms=["acteur", "actrice"]),
        w("architecte", "architecte", "архитектор", "Paul est architecte.", "Поль архитектор."),
        w("journaliste", "journaliste", "журналист", "Elle est journaliste.", "Она журналистка."),
        w("cuisinier", "cuisinier / cuisinière", "повар", "Il est cuisinier dans un restaurant.", "Он повар в ресторане.", forms=["cuisinier", "cuisinière"]),
        w("boulanger", "boulanger / boulangère", "пекарь", "Le boulanger fait du pain.", "Пекарь печёт хлеб.", forms=["boulanger", "boulangère"]),
        w("policier", "policier / policière", "полицейский", "Le policier est gentil.", "Полицейский добрый.", forms=["policier", "policière"]),
        w("chanteur", "chanteur / chanteuse", "певец / певица", "Angèle est chanteuse.", "Анжель — певица.", forms=["chanteur", "chanteuse"]),
        w("designer", "designer", "дизайнер", "Je suis designer.", "Я дизайнер."),
        w("photographe", "photographe", "фотограф", "Il est photographe.", "Он фотограф."),
        w("directeur", "directeur / directrice", "директор", "La directrice est là.", "Директор здесь.", forms=["directeur", "directrice"]),
        w("informaticien", "informaticien / informaticienne", "программист, айтишник", "Mon frère est informaticien.", "Мой брат айтишник.", forms=["informaticien", "informaticienne"]),
        w("voudrais", "je voudrais", "я бы хотел(а)", "Je voudrais un thé.", "Я бы хотела чай.", forms=["voudrais"]),
    ],
    "topics": [
        topic("t-modaux", "pouvoir, vouloir, devoir, savoir",
              ("ils (pouvoir) →", ["peuvent", "pouvent", "peut"]),
              ("je (vouloir) →", ["veux", "voux", "veut"]),
              ("nous (devoir) →", ["devons", "doivons", "devez"]),
              ("elle (savoir) →", ["sait", "sais", "savoit"])),
    ],
    "exercises": ex(
        J("pouvoir", [["je", "peux"], ["tu", "peux"], ["il", "peut"], ["nous", "pouvons"], ["vous", "pouvez"], ["ils", "peuvent"]]),
        J("vouloir", [["je", "veux"], ["tu", "veux"], ["elle", "veut"], ["nous", "voulons"], ["vous", "voulez"], ["elles", "veulent"]]),
        J("devoir", [["je", "dois"], ["tu", "dois"], ["on", "doit"], ["nous", "devons"], ["vous", "devez"], ["ils", "doivent"]]),
        J("savoir", [["je", "sais"], ["tu", "sais"], ["il", "sait"], ["nous", "savons"], ["vous", "savez"], ["ils", "savent"]]),
        G("Je ___ un café.", "Я хочу кофе. (vouloir)", "veux"),
        G("Tu ___ répéter ?", "Ты можешь повторить? (pouvoir)", "peux"),
        G("Nous ___ partir.", "Мы должны уходить. (devoir)", "devons"),
        G("Elle ___ nager.", "Она умеет плавать. (savoir)", "sait"),
        G("Ils ___ venir.", "Они хотят прийти. (vouloir)", "veulent"),
        C("Как вежливо заказать в кафе?", ["Je voudrais un thé, s’il vous plaît.", "Je veux un thé.", "Donne un thé."]),
        C("Как правильно сказать о профессии?", ["Je suis médecin.", "Je suis un médecin.", "Je suis le médecin."]),
        C("Женский род от acteur —", ["actrice", "acteuse", "acteure"]),
        L("Ils peuvent venir.", ["Il peut venir.", "Ils peuvent venir."], 1),
        M("Профессии", [["médecin", "врач"], ["avocate", "адвокат"], ["serveuse", "официантка"], ["boulanger", "пекарь"], ["chanteuse", "певица"]]),
        O("Собери фразу «Я не могу прийти»", ["peux", "Je", "ne", "pas", "venir"], "je ne peux pas venir"),
        D("Vous devez parler lentement.", "vous devez parler lentement"),
        T("Она журналистка.", "elle est journaliste"),
        T("Ты можешь прийти?", "tu peux venir", "peux-tu venir", "est-ce que tu peux venir"),
        T("Мы должны работать.", "nous devons travailler", "on doit travailler"),
    ),
    "homework": hw("Напиши о работе: кем ты работаешь или учишься, кем хочешь работать, что ты умеешь (je sais…), что можешь (je peux…) и что должна делать каждый день (je dois…). 5–6 предложений.",
                   "Je suis designer. Je veux travailler en France. Je sais dessiner. Je peux travailler à la maison. Je dois apprendre le français.", 20),
}

# ---------------------------------------------------------------- 9 октября
CONTENT["2026-10-09"] = {
    "topic": "Повторение présent · артикли · животные",
    "theory": [
        th("Определённый артикль: le, la, l’, les",
           "Когда говорим о чём-то известном или о чём-то вообще: J’aime les chats (люблю кошек вообще). Перед гласной — l’: l’oiseau.",
           exs=[["J’aime les chiens.", "Я люблю собак."], ["Le chat de Marie est noir.", "Кот Мари чёрный."]]),
        th("Неопределённый артикль: un, une, des",
           "Когда говорим о чём-то одном из многих, впервые: J’ai un chat (какой-то кот). Во множественном числе — des.",
           exs=[["J’ai un lapin.", "У меня есть кролик."], ["Il y a des oiseaux.", "Там (есть) птицы."]]),
        th("После отрицания — de",
           "un, une, des после ne … pas превращаются в de (d’ перед гласной): J’ai un chien → Je n’ai pas de chien.",
           exs=[["Je n’ai pas de chat.", "У меня нет кошки."], ["Il n’y a pas d’oiseaux.", "Птиц нет."]]),
        th("Частые ошибки новичков (из видео Easy French)",
           "Возраст — с avoir: j’ai 30 ans. Профессия — без артикля: je suis étudiante. После c’est — мужской род: c’est très beau. После aimer, adorer — определённый артикль: j’adore les pâtes.",
           exs=[["J’ai trente ans.", "Мне тридцать лет."], ["C’est très beau.", "Это очень красиво."], ["J’adore les pâtes.", "Обожаю пасту."]]),
    ],
    "vocab": [
        w("chien", "chien", "собака", "J’ai un chien.", "У меня есть собака.", "m", ["chiens", "chienne"]),
        w("chat", "chat", "кот, кошка", "Le chat dort.", "Кот спит.", "m", ["chats", "chatte"]),
        w("oiseau", "oiseau", "птица", "Un petit oiseau.", "Маленькая птичка.", "m", ["oiseaux"]),
        w("cheval", "cheval", "лошадь (мн. ч. chevaux)", "Les chevaux courent.", "Лошади бегут.", "m", ["chevaux"]),
        w("vache", "vache", "корова", "La vache mange.", "Корова ест.", "f", ["vaches"]),
        w("cochon", "cochon", "свинья", "Un petit cochon.", "Поросёнок.", "m", ["cochons"]),
        w("mouton-a", "mouton", "баран, барашек", "Dessine-moi un mouton !", "Нарисуй мне барашка!", "m", ["moutons"]),
        w("lapin", "lapin", "кролик", "Le lapin est blanc.", "Кролик белый.", "m", ["lapins"]),
        w("poisson", "poisson", "рыба", "Je mange du poisson.", "Я ем рыбу.", "m", ["poissons"]),
        w("souris", "souris", "мышь", "Le chat et la souris.", "Кот и мышь.", "f"),
        w("lion", "lion", "лев", "Le lion est le roi.", "Лев — король.", "m", ["lions"]),
        w("tigre", "tigre", "тигр", "Un grand tigre.", "Большой тигр.", "m", ["tigres"]),
        w("ours", "ours", "медведь", "L’ours dort en hiver.", "Медведь спит зимой.", "m"),
        w("singe", "singe", "обезьяна", "Le singe mange une banane.", "Обезьяна ест банан.", "m", ["singes"]),
        w("elephant", "éléphant", "слон", "L’éléphant est gris.", "Слон серый.", "m", ["éléphants"]),
        w("loup", "loup", "волк", "Le loup et l’agneau.", "Волк и ягнёнок.", "m", ["loups"]),
        w("renard", "renard", "лиса", "Le renard est rusé.", "Лиса хитрая.", "m", ["renards"]),
        w("canard", "canard", "утка", "Les canards nagent.", "Утки плавают.", "m", ["canards"]),
        w("poule", "poule", "курица", "La poule fait des œufs.", "Курица несёт яйца.", "f", ["poules"]),
        w("serpent", "serpent", "змея", "Un serpent boa.", "Удав.", "m", ["serpents"]),
        w("animal", "animal", "животное (мн. ч. animaux)", "J’adore les animaux.", "Обожаю животных.", "m", ["animaux"]),
    ],
    "topics": [
        topic("t-articles", "Артикли",
              ("«Я люблю кошек» (вообще)", ["J’aime les chats.", "J’aime des chats.", "J’aime chats."]),
              ("«У меня нет собаки»", ["Je n’ai pas de chien.", "Je n’ai pas un chien.", "Je n’ai pas le chien."]),
              ("___ oiseau", ["l’", "le", "la"])),
    ],
    "exercises": ex(
        C("___ chien", ["le", "la"]),
        C("___ souris", ["la", "le"]),
        C("___ oiseau", ["l’", "le", "la"]),
        G("J’ai ___ lapin.", "У меня есть кролик.", "un"),
        G("J’aime ___ chats.", "Я люблю кошек.", "les"),
        G("Je n’ai pas ___ chien.", "У меня нет собаки.", "de"),
        G("Il y a ___ oiseaux dans le jardin.", "В саду птицы.", "des"),
        J("разные глаголы", [["je (aller)", "vais"], ["tu (faire)", "fais"], ["il (prendre)", "prend"], ["nous (finir)", "finissons"], ["vous (être)", "êtes"], ["ils (avoir)", "ont"]], q="Повторение: поставь глагол в нужную форму"),
        C("Какая фраза правильная?", ["J’ai trente ans.", "Je suis trente ans."]),
        C("Какая фраза правильная?", ["C’est très beau.", "C’est très belle."]),
        C("Какая фраза правильная?", ["J’adore les pâtes.", "J’adore des pâtes."]),
        L("des chevaux", ["des chevaux", "deux chevaux", "des cheveux"]),
        M("Животные", [["le chien", "собака"], ["la vache", "корова"], ["le lapin", "кролик"], ["l’ours", "медведь"], ["le renard", "лиса"]]),
        O("Собери фразу «У неё две кошки»", ["a", "Elle", "chats", "deux"], "elle a deux chats"),
        D("Le chien et le chat dorment.", "le chien et le chat dorment"),
        T("У меня нет собаки.", "je n'ai pas de chien"),
        T("Я люблю кошек.", "j'aime les chats", "j'adore les chats"),
    ),
    "homework": hw("Опиши животное — своё или любимое: как его зовут, какое оно (grand, petit), что оно любит делать, где живёт. Если у тебя нет животного, напиши об этом: Je n’ai pas de…",
                   "J’ai un chat. Il s’appelle Moka. Il est petit et très gentil. Il aime dormir et manger. Je n’ai pas de chien.", 20),
}
