# -*- coding: utf-8 -*-
"""Грамматический практикум: трансформации и «найди ошибку» для каждого учебного дня.

X(инструкция, исходная фраза, *правильные ответы)
"""


def X(q, src, *a):
    return {"type": "transform", "q": q, "src": src, "a": list(a)}


FIX = "Найди и исправь ошибку — напиши фразу правильно"

DRILLS = {
    "2026-10-01": [
        X("Сократи (élision)", "je + ai", "j'ai"),
        X("Сократи (élision)", "le + ami", "l'ami"),
        X("Сократи (élision)", "la + école", "l'école"),
        X("Сократи (élision)", "je + m’appelle → «меня зовут Анна»", "je m'appelle anna"),
        X("Сделай вежливее: обратись на «вы»", "Salut !", "bonjour"),
        X("Ответь на «Merci !»", "Merci !", "de rien"),
        X(FIX, "Le ami de Marie.", "l'ami de marie"),
        X(FIX, "Le hôtel est petit.", "l'hôtel est petit"),
    ],
    "2026-10-02": [
        X("Поставь в лицо nous", "Je suis fatigué.", "nous sommes fatigués", "nous sommes fatiguées"),
        X("Поставь в лицо tu", "Vous êtes français ?", "tu es français"),
        X("Поставь в лицо nous", "Elles ont vingt ans.", "nous avons vingt ans"),
        X("Сделай отрицание", "Il a le temps.", "il n'a pas le temps"),
        X("Сделай отрицание", "Tu es à Paris.", "tu n'es pas à paris"),
        X("Поставь в лицо ils", "J’ai un ami.", "ils ont un ami"),
        X(FIX, "Je ne ai pas le temps.", "je n'ai pas le temps"),
        X(FIX, "Nous sont à Moscou.", "nous sommes à moscou"),
    ],
    "2026-10-05": [
        X("Поставь в лицо nous", "Je parle français.", "nous parlons français"),
        X("Поставь в лицо vous", "Tu aimes le café.", "vous aimez le café"),
        X("Поставь в лицо ils", "Nous mangeons à midi.", "ils mangent à midi"),
        X("Сделай отрицание", "Elle habite ici.", "elle n'habite pas ici"),
        X("Сделай отрицание", "J’aime le sport.", "je n'aime pas le sport"),
        X("Поставь в лицо je (повторение être)", "Ils sont à Paris.", "je suis à paris"),
        X(FIX, "Nous mangons ensemble.", "nous mangeons ensemble"),
        X(FIX, "Je aime Paris.", "j'aime paris"),
    ],
    "2026-10-06": [
        X("Поставь в лицо nous", "Je finis à six heures.", "nous finissons à six heures"),
        X("Поставь в лицо il", "Ils choisissent un film.", "il choisit un film"),
        X("Поставь в лицо nous", "Tu pars demain.", "nous partons demain"),
        X("Поставь в лицо ils", "Je dors bien.", "ils dorment bien"),
        X("Поставь в лицо nous", "Il lit un livre.", "nous lisons un livre"),
        X("Сделай отрицание", "Je comprends.", "je ne comprends pas"),
        X(FIX, "Nous finons le travail.", "nous finissons le travail"),
        X(FIX, "Vous partissez ?", "vous partez"),
    ],
    "2026-10-07": [
        X("Замени страну на «le Canada»", "Je vais en France.", "je vais au canada"),
        X("Замени страну на «le Japon»", "Il vient d’Italie.", "il vient du japon"),
        X("Замени страну на «l’Espagne»", "Nous allons aux États-Unis.", "nous allons en espagne"),
        X("Поставь в лицо ils", "Nous faisons du sport.", "ils font du sport"),
        X("Поставь в лицо je", "Vous prenez le bus.", "je prends le bus"),
        X("Поставь в лицо ils", "Tu viens avec nous.", "ils viennent avec nous"),
        X(FIX, "Vous faisez quoi ?", "vous faites quoi"),
        X(FIX, "Elle est italien.", "elle est italienne"),
    ],
    "2026-10-08": [
        X("Добавь vouloir: «хочу…»", "Je mange.", "je veux manger"),
        X("Добавь devoir: «должны…»", "Nous partons.", "nous devons partir"),
        X("Добавь savoir: «умеет…»", "Elle nage.", "elle sait nager"),
        X("Добавь pouvoir: «можешь…?»", "Tu viens ?", "tu peux venir"),
        X("Сделай отрицание", "Je peux venir.", "je ne peux pas venir"),
        X("Скажи вежливо (je voudrais)", "Je veux un café.", "je voudrais un café"),
        X(FIX, "Je suis un médecin.", "je suis médecin"),
        X(FIX, "Ils peut venir.", "ils peuvent venir"),
    ],
    "2026-10-09": [
        X("Сделай отрицание (un → de)", "J’ai un chien.", "je n'ai pas de chien"),
        X("Сделай отрицание (des → de)", "Il y a des oiseaux.", "il n'y a pas d'oiseaux"),
        X("Поставь во множественное число", "un cheval", "des chevaux"),
        X("Скажи «люблю … вообще»", "chats → J’aime…", "j'aime les chats"),
        X("Поставь в лицо nous", "Elle fait du sport.", "nous faisons du sport"),
        X("Поставь в лицо vous", "Je prends le métro.", "vous prenez le métro"),
        X(FIX, "Je suis trente ans.", "j'ai trente ans"),
        X(FIX, "J’adore des pâtes.", "j'adore les pâtes"),
    ],
    "2026-10-12": [
        X("Поставь в лицо nous", "Je me lève tôt.", "nous nous levons tôt"),
        X("Поставь в лицо je", "Il se couche tard.", "je me couche tard"),
        X("Поставь в лицо ils", "Elle s’habille vite.", "ils s'habillent vite"),
        X("Поставь в лицо vous", "Je me douche le matin.", "vous vous douchez le matin"),
        X("Сделай отрицание", "Tu te réveilles tôt.", "tu ne te réveilles pas tôt"),
        X("Добавь devoir: «я должна…»", "Je me lève.", "je dois me lever"),
        X(FIX, "Je se lave.", "je me lave"),
        X(FIX, "Nous nous levez.", "nous nous levons"),
    ],
    "2026-10-13": [
        X("Замени на притяжательное (его/её)", "le livre de Marie → … livre", "son livre"),
        X("Замени на притяжательное (их)", "la maison de mes parents → … maison", "leur maison"),
        X("Замени на притяжательное (наши)", "les amis de nous → … amis", "nos amis"),
        X("Поставь в лицо nous", "Je joue du piano.", "nous jouons du piano"),
        X(FIX, "Je joue du tennis.", "je joue au tennis"),
        X(FIX, "Il joue la guitare.", "il joue de la guitare"),
        X(FIX, "Elle fait natation.", "elle fait de la natation"),
        X(FIX, "C’est ma amie Léa.", "c'est mon amie léa"),
    ],
    "2026-10-14": [
        X("Поставь в женский род", "Il est heureux.", "elle est heureuse"),
        X("Поставь в женский род", "un garçon sportif → une fille…", "une fille sportive"),
        X("Поставь в женский род", "Il est beau.", "elle est belle"),
        X("Поставь в женский род", "Mon frère est gentil. → Ma sœur…", "ma sœur est gentille"),
        X("Поставь в женский род", "un vieux livre → une … maison", "une vieille maison"),
        X("Поставь в женский род", "Il est roux.", "elle est rousse"),
        X(FIX, "une intelligente femme", "une femme intelligente"),
        X(FIX, "un chat petit", "un petit chat"),
    ],
    "2026-10-15": [
        X("Соедини через d’abord … ensuite", "Je me lève. Je prends un café.", "d'abord je me lève ensuite je prends un café"),
        X("Добавь souvent", "Je lis.", "je lis souvent"),
        X("Скажи «никогда» (ne … jamais)", "Je bois du café le soir.", "je ne bois jamais de café le soir"),
        X("Поставь в лицо nous", "Elle s’habille.", "nous nous habillons"),
        X("Поставь в лицо je", "Nous finissons tard.", "je finis tard"),
        X(FIX, "Ma sœur est sportif.", "ma sœur est sportive"),
        X(FIX, "Il joue au violon.", "il joue du violon"),
        X(FIX, "Je jamais mange de viande.", "je ne mange jamais de viande"),
    ],
    "2026-10-16": [
        X("Напиши время словами", "3:30", "il est trois heures et demie"),
        X("Напиши время словами", "7:45", "il est huit heures moins le quart"),
        X("Напиши время словами", "00:00", "il est minuit"),
        X("Скажи «по понедельникам»", "Je travaille lundi.", "je travaille le lundi"),
        X(FIX, "J’ai mal à le ventre.", "j'ai mal au ventre"),
        X(FIX, "J’ai mal à les dents.", "j'ai mal aux dents"),
        X(FIX, "Mon anniversaire est à mai.", "mon anniversaire est en mai"),
        X(FIX, "Je suis de la fièvre.", "j'ai de la fièvre"),
    ],
    "2026-10-19": [
        X("Напиши словами", "17", "dix-sept"),
        X("Напиши словами", "71", "soixante et onze"),
        X("Напиши словами", "80", "quatre-vingts"),
        X("Напиши словами", "95", "quatre-vingt-quinze"),
        X("Напиши словами", "21", "vingt et un"),
        X("Напиши словами", "300", "trois cents"),
        X("Напиши фразу словами", "J’ai 33 ans.", "j'ai trente-trois ans"),
        X(FIX, "le deux jour", "le deuxième jour"),
    ],
    "2026-10-20": [
        X("Поставь во множественное число", "un chapeau", "des chapeaux"),
        X("Поставь во множественное число", "un journal", "des journaux"),
        X("Поставь во множественное число", "un œil", "des yeux"),
        X("Поставь во множественное число", "une robe bleue", "des robes bleues"),
        X("Поставь во множественное число", "le beau manteau", "les beaux manteaux"),
        X("Поставь в лицо nous", "Elle porte un jean.", "nous portons un jean"),
        X(FIX, "des chevals", "des chevaux"),
        X(FIX, "J’ai mal au jambe.", "j'ai mal à la jambe"),
    ],
    "2026-10-21": [
        X("Поставь в futur proche", "Je mange.", "je vais manger"),
        X("Поставь в futur proche", "Nous partons.", "nous allons partir"),
        X("Поставь в futur proche", "Ils arrivent demain.", "ils vont arriver demain"),
        X("Поставь в futur proche", "Tu travailles ?", "tu vas travailler"),
        X("Поставь в futur proche", "Je me repose.", "je vais me reposer"),
        X("Сделай отрицание", "Je vais sortir.", "je ne vais pas sortir"),
        X(FIX, "Je vais à manger.", "je vais manger"),
        X(FIX, "Elle va arrive.", "elle va arriver"),
    ],
    "2026-10-22": [
        X("Поставь в impératif", "Tu prends le bus.", "prends le bus"),
        X("Поставь в impératif", "Vous tournez à gauche.", "tournez à gauche"),
        X("Поставь в impératif", "Nous allons au cinéma.", "allons au cinéma"),
        X("Поставь в impératif", "Tu es gentil.", "sois gentil"),
        X("Поставь в impératif", "Tu te dépêches.", "dépêche-toi"),
        X("Сделай отрицание", "Parle !", "ne parle pas"),
        X(FIX, "Regardes !", "regarde"),
        X(FIX, "Allez tout droite.", "allez tout droit"),
    ],
    "2026-10-23": [
        X("Скажи «только что» (venir de)", "Je mange.", "je viens de manger"),
        X("Скажи «только что» (venir de)", "Il arrive.", "il vient d'arriver"),
        X("Скажи «только что» (venir de)", "Nous finissons.", "nous venons de finir"),
        X("Переведи в будущее (futur proche)", "Je viens de partir.", "je vais partir"),
        X("Переведи в «только что»", "Ils vont voir le film.", "ils viennent de voir le film"),
        X("Скажи, что он носит", "Il a des lunettes. → Il … des lunettes.", "il porte des lunettes"),
        X(FIX, "Il vient de arriver.", "il vient d'arriver"),
        X(FIX, "Elle est les cheveux longs.", "elle a les cheveux longs"),
    ],
    "2026-10-26": [
        X("Поставь в passé composé", "Je mange.", "j'ai mangé"),
        X("Поставь в passé composé", "Nous finissons.", "nous avons fini"),
        X("Поставь в passé composé", "Ils attendent le bus.", "ils ont attendu le bus"),
        X("Поставь в passé composé", "Tu regardes le film.", "tu as regardé le film"),
        X("Сделай отрицание", "J’ai mangé.", "je n'ai pas mangé"),
        X("Скажи о вчерашнем дне", "Je vais travailler. → Hier…", "hier j'ai travaillé"),
        X(FIX, "J’ai finé.", "j'ai fini"),
        X(FIX, "Il fait pluie.", "il pleut"),
    ],
    "2026-10-27": [
        X("Поставь в passé composé", "Je fais du sport.", "j'ai fait du sport"),
        X("Поставь в passé composé", "Il prend le train.", "il a pris le train"),
        X("Поставь в passé composé", "Nous voyons un film.", "nous avons vu un film"),
        X("Поставь в passé composé", "Elle lit un livre.", "elle a lu un livre"),
        X("Поставь в passé composé", "Tu bois un café.", "tu as bu un café"),
        X("Поставь в passé composé", "Ils écrivent un message.", "ils ont écrit un message"),
        X("Поставь в passé composé с отрицанием", "Je ne peux pas venir.", "je n'ai pas pu venir"),
        X(FIX, "J’ai prendu le métro.", "j'ai pris le métro"),
    ],
    "2026-10-28": [
        X("Поставь в passé composé (говорит женщина)", "Je vais à Paris.", "je suis allée à paris"),
        X("Поставь в passé composé", "Il arrive.", "il est arrivé"),
        X("Поставь в passé composé", "Elles partent.", "elles sont parties"),
        X("Поставь в passé composé (мы — смешанная группа)", "Nous restons à la maison.", "nous sommes restés à la maison"),
        X("Поставь в passé composé (говорит женщина)", "Je me lève.", "je me suis levée"),
        X(FIX, "Elle a allé au cinéma.", "elle est allée au cinéma"),
        X(FIX, "Il est mangé une pomme.", "il a mangé une pomme"),
        X(FIX, "La banque est à côté le café.", "la banque est à côté du café"),
    ],
    "2026-10-29": [
        X("Добавь «уже год, до сих пор»", "J’habite ici.", "j'habite ici depuis un an"),
        X("Добавь «8 часов»", "J’ai dormi.", "j'ai dormi pendant huit heures"),
        X("Добавь «10 минут назад»", "Il est parti.", "il est parti il y a dix minutes"),
        X("Поставь в passé composé (говорит женщина)", "Je vais au cinéma.", "je suis allée au cinéma"),
        X("Поставь в futur proche", "Je vais au cinéma.", "je vais aller au cinéma"),
        X("Скажи «только что» (venir de)", "Je vais au cinéma.", "je viens d'aller au cinéma"),
        X(FIX, "en printemps", "au printemps"),
        X(FIX, "Je vais à France.", "je vais en france"),
    ],
}
